#pragma once

//正服取得的所有Packet Header
class EPacketFlags
{
public:
	enum CLIENT_PACKET : short
	{
		CP_DUMMY_CODE = 0x64,

		CP_BEGIN_SOCKET = 0x65,
		CP_SecurityPacket = 0x66,
		CP_PermissionRequest = 0x67,
		CP_LoginBasicInfo = 0x68,
		CP_CheckLoginAuthInfo = 0x69,
		CP_SelectWorld = 0x6A,
		CP_CheckSPWRequest = 0x6B,
		CP_ClientLodingTimeLog = 0x6C,
		CP_CheckSPWExistRequest = 0x6D,
		CP_MigrateIn = 0x6E,
		CP_SelectCharacter = 0x6F,
		CP_SelectGoToStarPlanet = 0x70,
		CP_SelectAccount = 0x71,
		CP_WorldInfoRequest = 0x72,
		CP_WorldInfoForShiningRequest = 0x73,
		CP_CheckDuplicatedID = 0x74,
		CP_LogoutWorld = 0x75,
		CP_PermissionRequest_Fake = 0x76,
		CP_CheckLoginAuthInfo_Fake = 0x77,
		CP_CreateMapleAccount_Fake = 0x78,
		CP_SelectAccount_Fake = 0x79,
		CP_SelectWorld_Fake = 0x7A,
		CP_SelectCharacter_Fake = 0x7B,
		CP_CreateNewCharacter_Fake = 0x7C,
		CP_CreateNewCharacter = 0x7D,
		CP_CreateNewCharacterInCS = 0x7E,
		CP_CreateNewCharacter_PremiumAdventurer = 0x7F,
		CP_DeleteCharacter = 0x80,
		CP_ReservedDeleteCharacterConfirm = 0x81,
		CP_ReservedDeleteCharacterCancel = 0x82,
		CP_RenameCharacter = 0x83,
		CP_AliveAck_Fake = 0x84,
		CP_ExceptionLog = 0x85,
		CP_PrivateServerPacket = 0x86,
		CP_ResetLoginStateOnCheckOTP = 0x87,
		CP_ChangeSPWRequest = 0x88,
		CP_CheckSPWRequest_Fake = 0x89,
		CP_CheckOTPRequest = 0x8A,
		CP_CheckDeleteCharacterOTP = 0x8B,
		CP_CheckOTPForWebLaunchingRequest = 0x8C,
		CP_CreateSecurityHandle = 0x8D,
		CP_LogForDebug = 0x8E,
		CP_AlbaRequest = 0x8F,
		CP_UpdateCharacterCard = 0x90,
		CP_CheckCenterAndGameAreConnected = 0x91,
		CP_ResponseToCheckAliveAck_Fake = 0x92,
		CP_CreateMapleAccount = 0x93,
		CP_AliveAck = 0x94,
		CP_ResponseToCheckAliveAck = 0x95,
		CP_ClientDumpLog = 0x96,
		CP_CrcErrorLog = 0x97,
		CP_PerformanceInfoProvidedConsent = 0x98,
		CP_CheckHotfix = 0x99,
		CP_ClientExceptionInfo = 0x9A,
		CP_WvsSetUpStep = 0x9B,
		CP_WvsCrashCallback = 0x9C,
		CP_END_SOCKET = 0x9D,

		CP_BEGIN_USER = 0x9E,
		CP_UserTransferFieldRequest = 0xB3,// 0x9F,
		CP_UserTransferChannelRequest,// = 0xA0,
		CP_UserTransferToHubRequest,// = 0xA1,
		CP_WorldTransferRequest,// = 0xA2,
		CP_WorldTransferShinningStarRequest,// = 0xA3,
		CP_UserMigrateToCashShopRequest,// = 0xA4,
		CP_UserMigrateToPvpRequest,// = 0xA5,
		CP_PartyMigrateToPvpRequest,// = 0xA6,
		CP_UserMigrateToMonsterFarm,// = 0xA7,
		CP_UserMigrateToMonsterFarmByInviteItem,// = 0xA8,
		CP_UserTransferAswanRequest,// = 0xA9,
		CP_UserTransferAswanReadyRequest,// = 0xAA,
		CP_AswanRetireRequest,// = 0xAB,
		CP_UserRequestPvPStatus,// = 0xAC,
		CP_UserMigrateToPveRequest,// = 0xAD,
		CP_UserUnk1,
		CP_UserUnk2,
		CP_UserMove,// = 0xAE,
		CP_UserSitRequest,// = 0xAF,
		CP_UserPortableChairSitRequest,// = 0xB0,
		CP_UserEmoticonItemUseRequest,// = 0xB1,
		CP_UserDanceStopRequest,// = 0xB2,
		CP_UserMeleeAttack,// = 0xB3,
		CP_UserShootAttack,// = 0xB4,
		CP_UserMagicAttack,// = 0xB5,
		CP_UserBodyAttack,// = 0xB6,
		CP_UserAreaDotAttack,// = 0xB7,
		CP_UserMovingShootAttackPrepare,// = 0xB8,
		CP_UserHit,// = 0xB9,
		CP_UserAttackUser,// = 0xBA,
		CP_UserChat,// = 0xBB,
		CP_UserADBoardClose,// = 0xBC,
		CP_UserEmotion,// = 0xBD,
		CP_AndroidEmotion,// = 0xBE,
		CP_UserActivateEffectItem,// = 0xBF,
		CP_UserMonkeyEffectItem,// = 0xC0,
		CP_UserActivateNickItem,// = 0xC1,
		CP_UserActivateDamageSkin,// = 0xC2,
		CP_UserActivateDamageSkin_Premium,// = 0xC3,
		CP_UserDamageSkinSaveRequest,// = 0xC4,
		CP_UserDefaultWingItem,// = 0xC5,
		CP_UserKaiserTransformWing,// = 0xC6,
		CP_UserKaiserTransformTail,// = 0xC7,
		CP_UserUpgradeTombEffect,// = 0xC8,
		CP_UserHP,// = 0xC9,
		CP_Premium,// = 0xCA,
		CP_UserBanMapByMob,// = 0xCB,
		CP_UserMonsterBookSetCover,// = 0xCC,
		CP_UserSelectNpc,// = 0xCD,
		CP_UserRemoteShopOpenRequest,// = 0xCE,
		CP_UserScriptMessageAnswer,// = 0xCF,
		CP_UserShopRequest,// = 0xD0,
		CP_UserTrunkRequest,// = 0xD1,
		CP_UserEntrustedShopRequest,// = 0xD2,
		CP_UserStoreBankRequest,// = 0xD3,
		CP_UserParcelRequest,// = 0xD4,
		CP_UserEffectLocal,// = 0xD5,
		CP_UserSpecialEffectLocal,// = 0xD6,
		CP_UserFinalAttackRequest,// = 0xD7,
		CP_UserCreateAreaDotRequest,// = 0xD8,
		CP_UserCreateHolidomRequest,// = 0xD9,
		CP_ReqMakingSkillEff,// = 0xDA,
		CP_ShopScannerRequest,// = 0xDB,
		CP_ShopLinkRequest,// = 0xDC,
		CP_AuctionRequest,// = 0xDD,
		CP_AdminShopRequest,// = 0xDE,
		CP_UserGatherItemRequest,// = 0xDF,
		CP_UserSortItemRequest,// = 0xE0,
		CP_UserChangeSlotPositionRequest,// = 0xE1,
		CP_UserTextEquipInfo,// = 0xE2,
		CP_UserPopOrPushBagItemToInven,// = 0xE3,
		CP_UserBagToBagItem,// = 0xE4,
		CP_UserPourInBagToBag,// = 0xE5,
		CP_UserStatChangeItemUseRequest,// = 0xE6,
		CP_UserStatChangeItemCancelRequest,// = 0xE7,
		CP_UserStatChangeByPortableChairRequest,// = 0xE8,
		CP_UserMobSummonItemUseRequest,// = 0xE9,
		CP_UserPetFoodItemUseRequest,// = 0xEA,
		CP_UserTamingMobFoodItemUseRequest,// = 0xEB,
		CP_UserScriptItemUseRequest,// = 0xEC,
		CP_UserRecipeOpenItemUseRequest,// = 0xED,
		CP_UserConsumeCashItemUseRequest,// = 0xEE,
		CP_UserAdditionalSlotExtendItemUseRequest,// = 0xEF,
		CP_UserCashPetPickUpOnOffRequest,// = 0xF0,
		CP_UserCashPetSkillSettingRequest,// = 0xF1,
		CP_UserOptionChangeRequest,// = 0xF2,
		CP_UserDestroyPetItemRequest,// = 0xF3,
		CP_UserBridleItemUseRequest,// = 0xF4,
		CP_UserSkillLearnItemUseRequest,// = 0xF5,
		CP_UserSkillResetItemUseRequest,// = 0xF6,
		CP_UserAbilityResetItemUseRequest,// = 0xF7,
		CP_UserAbilityChangeItemUseRequest,// = 0xF8,
		CP_UserExpConsumeItemUseRequest,// = 0xF9,
		CP_UserMonsterLifeInviteItemUseRequest,// = 0xFA,
		CP_UserExpItemGetRequest,// = 0xFB,
		CP_UserCharSlotIncItemUseRequest,// = 0xFC,
		CP_UserCharRenameItemUseRequest,// = 0xFD,
		CP_UserKaiserColorChangeItemUseRequest,// = 0xFE,
		CP_UserShopScannerItemUseRequest,// = 0xFF,
		CP_UserMapTransferItemUseRequest,// = 0x100,
		CP_UserPortalScrollUseRequest,// = 0x101,
		CP_UserFieldTransferRequest,// = 0x102,
		CP_UserUpgradeItemUseRequest,// = 0x103,
		CP_UserUpgradeAssistItemUseRequest,// = 0x104,
		CP_UserHyperUpgradeItemUseRequest,// = 0x105,
		CP_UserExItemUpgradeItemUseRequest,// = 0x106,
		CP_UserKarmaConsumeItemUseRequest,// = 0x107,
		CP_UserEventUpgradeItemUseRequest,// = 0x108,
		CP_UserItemOptionUpgradeItemUseRequest,// = 0x109,
		CP_UserAdditionalOptUpgradeItemUseRequest,// = 0x10A,
		CP_UserItemSlotExtendItemUseRequest,// = 0x10B,
		CP_UserWeaponTempItemOptionRequest,// = 0x10C,
		CP_UserItemSkillSocketUpgradeItemUseRequest,// = 0x10D,
		CP_UserItemSkillOptionUpgradeItemUseRequest,// = 0x10E,
		CP_UserFreeMiracleCubeItemUseRequest,// = 0x10F,
		CP_UserEquipmentEnchantWithSingleUIRequest,// = 0x110,
		CP_UserUIOpenItemUseRequest,// = 0x111,
		CP_UserBagItemUseRequest,// = 0x112,
		CP_UserItemReleaseRequest,// = 0x113,
		CP_UserMemorialCubeOptionRequest,// = 0x114,
		CP_UserUseNaviFlyingSkillRequest,// = 0x115,
		CP_UserToadsHammerRequest,// = 0x116,
		CP_UserToadsHammerHelpRequest,// = 0x117,
		CP_UserChangeSoulCollectionRequest,// = 0x118,
		CP_UserSelectSoulSkillUpRequest,// = 0x119,
		CP_UserUnk3,
		CP_UserUnk4,
		CP_UserUnk5,
		CP_UserUnk6,
		CP_UserUnk7,
		CP_UserUnk8,
		CP_UserAbilityUpRequest,// = 0x11A,
		CP_UserAbilityMassUpRequest,// = 0x11B,
		CP_UserUnk9,
		CP_UserDotHeal,// = 0x11C,
		CP_UserChangeStatRequest,// = 0x11D,
		CP_UserChangeStatRequestByItemOption,// = 0x11E,
		CP_SetSonOfLinkedSkillRequest,// = 0x11F,
		CP_UserUnkA,
		CP_UserSkillUpRequest,// = 0x120,
		CP_UserSkillUseRequest,// = 0x121,
		CP_UserSkillCancelRequest,// = 0x122,
		CP_UserSkillPrepareRequest,// = 0x123,
		CP_UserUnkB,
		CP_UserUnkC,
		CP_UserDropMoneyRequest,// = 0x124,
		CP_UserGivePopularityRequest,// = 0x125,
		CP_UserPartyRequest,// = 0x126,
		CP_UserCharacterInfoRequest,// = 0x127,
		CP_UserActivatePetRequest,// = 0x128,
		CP_UserRegisterPetAutoBuffRequest,// = 0x129,
		CP_UserTemporaryStatUpdateRequest,// = 0x12A,
		CP_UserPortalScriptRequest,// = 0x12B,
		CP_UserPortalTeleportRequest,// = 0x12C,
		CP_UserCallingTeleportRequest,// = 0x12D,
		CP_UserMapTransferRequest,// = 0x12E,
		CP_UserAntiMacroItemUseRequest,// = 0x12F,
		CP_UserAntiMacroSkillUseRequest,// = 0x130,
		CP_UserOldAntiMacroQuestionResult,// = 0x131,
		CP_UserAntiMacroRefreshRequest,// = 0x132,
		CP_UserClaimRequest,// = 0x133,
		CP_UserQuestRequest,// = 0x134,
		CP_UserMedalReissueRequest,// = 0x135,
		CP_UserCalcDamageStatSetRequest,// = 0x136,
		CP_UserB2BodyRequest,// = 0x137,
		CP_UserThrowGrenade,// = 0x138,
		CP_UserDestroyGrenade,// = 0x139,
		CP_UserCreateAuraByGrenade,// = 0x13A,
		CP_UserSetMoveGrenade,// = 0x13B,
		CP_UserMacroSysDataModified,// = 0x13C,
		CP_UserSelectNpcItemUseRequest,// = 0x13D,
		CP_UserLotteryItemUseRequest,// = 0x13E,
		CP_UserRouletteStartRequest,// = 0x13F,
		CP_UserRouletteResultRequest,// = 0x140,
		CP_UserItemMakeRequest,// = 0x141,
		CP_UserRepairDurabilityAll,// = 0x142,
		CP_UserRepairDurability,// = 0x143,
		CP_UserQuestRecordSetState,// = 0x144,
		CP_UserClientTimerEndRequest,// = 0x145,
		CP_UserClientResolutionResult,// = 0x146,
		CP_UserFollowCharacterRequest,// = 0x147,
		CP_UserFollowCharacterWithdraw,// = 0x148,
		CP_UserSelectPQReward,// = 0x149,
		CP_UserRequestPQReward,// = 0x14A,
		CP_SetPassenserResult,// = 0x14B,
		CP_UserRequestInstanceTable = 0x16B,// = 0x14C,
		CP_UserRequestCreateItemPot,// = 0x14D,
		CP_UserRequestRemoveItemPot,// = 0x14E,
		CP_UserRequestIncItemPotLifeSatiety,// = 0x14F,
		CP_UserRequestCureItemPotLifeSick,// = 0x150,
		CP_UserRequestComplateToItemPot,// = 0x151,
		CP_UserRequestRespawn,// = 0x152,
		CP_UserConsumeHairItemUseRequest,// = 0x153,
		CP_UserForceAtomCollision,// = 0x154,
		CP_UserDebuffObjCollision,// = 0x155,
		CP_UserUpdateLapidification,// = 0x156,
		CP_UserRequestCharacterPotentialSkillRandSet,// = 0x157,
		CP_UserRequestCharacterPotentialSkillRandSetUI,// = 0x158,
		CP_UserRequestOccumpationData,// = 0x159,
		CP_UserRequestAswanTimeTableClientInit,// = 0x15A,
		CP_UserProtectBuffOnDieItemRequest,// = 0x15B,
		CP_UserProtectBuffOnDieMaplePointRequest,// = 0x15C,
		CP_UserProtectExpOnDieMaplePointRequest,// = 0x15D,
		CP_UserKeyDownAreaMoving,// = 0x15E,
		CP_UserCheckWeddingExRequest,// = 0x15F,
		CP_UserCatchDebuffCollision,// = 0x160,
		CP_UserAffectedAreaCreated,// = 0x161,
		CP_UserAffectedAreaRemoved,// = 0x162,
		CP_UserDazzleHit,// = 0x163,
		CP_UserMesoExchangeRequest,// = 0x164,
		CP_ZeroTag,// = 0x165,
		CP_ZeroShareCashEquipPart,// = 0x166,
		CP_ZeroLastAssistState,// = 0x167,
		CP_UserShootAttackInFPS,// = 0x168,
		CP_UserLuckyItemUseRequest,// = 0x169,
		CP_UserMobMoveAbilityChange,// = 0x16A,
		CP_UserDragonAction,// = 0x16B,
		CP_UserDragonBreathEarthEffect,// = 0x16C,
		CP_UserRenameRequest,// = 0x16D,
		CP_BroadcastMsg,// = 0x16E,
		CP_GroupMessage,// = 0x16F,
		CP_FieldUniverseMessage,// = 0x170,
		CP_Whisper,// = 0x171,
		CP_Messenger,// = 0x172,
		CP_MiniRoom,// = 0x173,
		CP_PartyRequest,// = 0x174,
		CP_PartyResult,// = 0x175,
		CP_PartyInvitableSet,// = 0x176,
		CP_ExpeditionRequest,// = 0x177,
		CP_PartyAdverRequest,// = 0x178,
		CP_UrusPartyRequest,// = 0x179,
		CP_GuildRequest,// = 0x17A,
		CP_GuildResult,// = 0x17B,
		CP_GuildJoinRequest,// = 0x17C,
		CP_GuildJoinCancelRequest,// = 0x17D,
		CP_GuildJoinAccept,// = 0x17E,
		CP_GuildJoinReject,// = 0x17F,
		CP_GuildContentRankRequest,// = 0x180,
		CP_TowerRankRequest,// = 0x181,
		CP_Admin,// = 0x182,
		CP_Log,// = 0x183,
		CP_FriendRequest,// = 0x184,
		CP_StarFriendRequest,// = 0x185,
		CP_StarPlanetPointRequest,// = 0x186,
		CP_LoadAccountIDOfCharacterFriendRequest,// = 0x187,
		CP_MemoRequest,// = 0x188,
		CP_MemoFlagRequest,// = 0x189,
		CP_EnterTownPortalRequest,// = 0x18A,
		CP_EnterRandomPortalRequest,// = 0x18B,
		CP_EnterOpenGateRequest,// = 0x18C,
		CP_SlideRequest,// = 0x18D,
		CP_FuncKeyMappedModified = 0x1B5, //0x18E,
		CP_RPSGame,// = 0x18F,
		CP_GSRPSGame,// = 0x190,
		CP_StarPlanet_GSRPSGame,// = 0x191,
		CP_GSRPSForceSelect,// = 0x192,
		CP_MarriageRequest,// = 0x193,
		CP_WeddingWishListRequest,// = 0x194,
		CP_GuestBless,// = 0x195,
		CP_BoobyTrapAlert,// = 0x196,
		CP_StalkBegin,// = 0x197,
		CP_AllianceRequest,// = 0x198,
		CP_AllianceResult,// = 0x199,
		CP_FamilyChartRequest,// = 0x19A,
		CP_FamilyInfoRequest,// = 0x19B,
		CP_FamilyRegisterJunior,// = 0x19C,
		CP_FamilyUnregisterJunior,// = 0x19D,
		CP_FamilyUnregisterParent,// = 0x19E,
		CP_FamilyJoinResult,// = 0x19F,
		CP_FamilyUsePrivilege,// = 0x1A0,
		CP_FamilySetPrecept,// = 0x1A1,
		CP_FamilySummonResult,// = 0x1A2,
		CP_TalkToTutor,// = 0x1A3,
		CP_TalkToPartner,// = 0x1A4,
		CP_UserSwitchRP,// = 0x1A5,
		CP_RequestIncCombo,// = 0x1A6,
		CP_RequestDecCombo,// = 0x1A7,
		CP_RequestSetBlessOfDarkness,// = 0x1A8,
		CP_RequestSetHpBaseDamage,// = 0x1A9,
		CP_MobCrcKeyChangedReply,// = 0x1AA,
		CP_MobCrcDataResult,// = 0x1AB,
		CP_MakingSkillRequest,// = 0x1AC,
		CP_BroadcastEffectToSplit,// = 0x1AD,
		CP_BroadcastOneTimeActionToSplit,// = 0x1AE,
		CP_BroadcastAffectedEffectToSplit,// = 0x1AF,
		CP_DebugOnlyCommand,// = 0x1B0,
		CP_MicroBuffEndTime,// = 0x1B1,
		CP_RequestSessionValue,// = 0x1B2,
		CP_UserTransferFreeMarketRequest,// = 0x1B3,
		CP_UserRequestSetStealSkillSlot,// = 0x1B4,
		CP_UserRequestStealSkillMemory,// = 0x1B5,
		CP_UserRequestStealSkillList,// = 0x1B6,
		CP_UserRequestStealSkill,// = 0x1B7,
		CP_RewardMobListRequest,// = 0x1B8,
		CP_UserLvUpGuideNotice,// = 0x1B9,
		CP_ResetCrossHunterAlert,// = 0x1BA,
		CP_CrossHunterCompleteRequest,// = 0x1BB,
		CP_CrossHunterShopRequest,// = 0x1BC,
		CP_UserEquipSlotLevelMinusItemUseRequest,// = 0x1BD,
		CP_BoardGameRequest,// = 0x1BE,
		CP_UserRequestFlyingSwordStart,// = 0x1BF,
		CP_BingoRequest,// = 0x1C0,
		CP_BingoCassandraRequest,// = 0x1C1,
		CP_ActionBarRequest,// = 0x1C2,
		CP_UserRequestSetOffTrinity,// = 0x1C3,
		CP_MesoRangerRequest,// = 0x1C4,
		CP_UserRequestSetSmashCount,// = 0x1C5,
		CP_UserHyperSkillUpRequest,// = 0x1C6,
		CP_UserHyperSkillResetRequset,// = 0x1C7,
		CP_UserHyperStatSkillUpRequest,// = 0x1C8,
		CP_UserHyperStatSkillResetRequest,// = 0x1C9,
		CP_UserSetDressChangedRequest,// = 0x1CA,
		CP_EntryRecordRequest,// = 0x1CB,
		CP_SetMaxGauge,// = 0x1CC,
		CP_UserReturnEffectResponse,// = 0x1CD,
		CP_GetServerTime,// = 0x1CE,
		CP_GetCharacterPosition,// = 0x1CF,
		CP_UserRequestChangeMobZoneState,// = 0x1D0,
		CP_EvolvingRequest,// = 0x1D1,
		CP_UserMixerRequest,// = 0x1D2,
		CP_SummonEventReward,// = 0x1D3,
		CP_MysticFieldMove,// = 0x1D4,
		CP_YutGameRequest,// = 0x1D5,
		CP_UserJewelCraftRequest,// = 0x1D6,
		CP_ValuePackRequest,// = 0x1D7,
		CP_RequestReloginCookie = 0x204,// = 0x1D8,
		CP_WaitQueueRequest = 0x1D9,
		CP_CheckTrickOrTreatRequest = 0x1DA,
		CP_MonsterFarmMigrateOutRequest = 0x1DB,
		CP_HalloweenCandyRankingRequest = 0x1DC,
		CP_GetRewardRequest = 0x1DD,
		CP_MapleStyleBonusRequest = 0x1DE,
		CP_MapleStyleAdviceRequest = 0x1DF,
		CP_MapleStyleSetScoreRequest = 0x1E0,
		CP_Mentoring = 0x1E1,
		CP_GetLotteryResult = 0x1E2,
		CP_RootabyssEnterRequest = 0x1E3,
		CP_UserSetItemAction = 0x1E4,
		CP_UserSetBitsCase = 0x1E5,
		CP_UserSetBitsSlot = 0x1E6,
		CP_UserAntiMacroQuestionResult = 0x1E7,
		CP_UserPinkbeanRolling = 0x1E8,
		CP_UserPinkbeanYoYoStack = 0x1E9,
		CP_UserQuickMoveScript = 0x1EA,
		CP_TimeGateRequest = 0x1EB,
		CP_UserSelectAndroid = 0x1EC,
		CP_UserCompleteNpcSpeech = 0x1ED,
		CP_UserCompleteAnotherUserCheck = 0x1EE,
		CP_UserCompleteComboKillCountCheck = 0x1EF,
		CP_UserCompleteMultiKillCountCheck = 0x1F0,
		CP_UserCompleteMultiKillCheck = 0x1F1,
		CP_UserDamageOnFallingCheck = 0x1F2,
		CP_UserCompletePersonalShopBuyCheck = 0x1F3,
		CP_UserDailyCommitmentCheck = 0x1F4,
		CP_UserMobDropMesoPickup = 0x1F5,
		CP_UserBreakTimeFieldEnter = 0x1F6,
		CP_UserRunActQuest = 0x1F7,
		CP_JournalAvatarRequest = 0x1F8,
		CP_RequestEventList = 0x1F9,
		CP_UserSignRequest = 0x1FA,
		CP_AddAttackReset = 0x1FB,
		CP_SetEventNameTag = 0x1FC,
		CP_UserAffectedAreaRemoveByTime = 0x1FD,
		CP_RequestFreeChangeJob = 0x1FE,
		CP_LibraryStartScript = 0x1FF,
		CP_ChannelUserCountRequest = 0x200,
		CP_UnUrusSelectedSkillList = 0x201,
		CP_SoulDungeonSys = 0x202,
		CP_UserCoordinationContestRequest = 0x203,
		CP_UserSoulEffectRequest = 0x204,
		CP_UserSpinOffNewModifyRequest = 0x205,
		CP_BlackList = 0x206,
		CP_SkillHelperPopup = 0x207,
		CP_Blockbuster = 0x208,
		CP_MTalkOfflineAccountFriendsNameRequest = 0x209,
		CP_CharacterBurning = 0x20A,
		CP_UpdateCharacterSelectList = 0x20B,
		CP_DirectGoToField = 0x20C,
		CP_TryRegisterTeleport = 0x20D,
		CP_UserTowerChairSetting = 0x20E,
		CP_UserLastCollectMonsterReset = 0x20F,
		CP_EndOverHeat = 0x210,
		CP_TradeKingShopReq = 0x211,
		CP_TradeKingShopInfoReq = 0x212,

		CP_BEGIN_PET = 0x213,
		CP_PetMove = 0x214,
		CP_PetAction = 0x215,
		CP_PetInteractionRequest = 0x216,
		CP_PetDropPickUpRequest = 0x217,
		CP_PetStatChangeItemUseRequest = 0x218,
		CP_PetUpdateExceptionListRequest = 0x219,
		CP_PetFoodItemUseRequest = 0x21A,
		CP_PetOpenShop = 0x21B,
		CP_END_PET = 0x21C,

		CP_BEGIN_SKILLPET = 0x21D,
		CP_SkillPetMove = 0x21E,
		CP_SkillPetAction = 0x21F,
		CP_SkillPetState = 0x220,
		CP_SkillPetDropPickUpRequest = 0x221,
		CP_SkillPetUpdateExceptionListRequest = 0x222,
		CP_END_SKILLPET = 0x223,

		CP_BEGIN_SUMMONED = 0x224,
		CP_SummonedMove = 0x225,
		CP_SummonedAttack = 0x226,
		CP_SummonedHit = 0x227,
		CP_SummonedSkill = 0x228,
		CP_Remove = 0x229,
		CP_SummonedAttackPvP = 0x22A,
		CP_SummonedAction = 0x22B,
		CP_SummonedAssistAttackDone = 0x22C,
		CP_END_SUMMONED = 0x22D,

		CP_BEGIN_DRAGON = 0x22E,
		CP_DragonMove = 0x22F,
		CP_DragonGlide = 0x230,
		CP_END_DRAGON = 0x231,

		CP_BEGIN_ANDROID = 0x232,
		CP_AndroidMove = 0x233,
		CP_AndroidActionSet = 0x234,
		CP_END_ANDROID = 0x235,

		CP_BEGIN_FOXMAN = 0x236,
		CP_FoxManMove = 0x237,
		CP_FoxManActionSetUseRequest = 0x238,
		CP_END_FOXMAN = 0x239,

		CP_QuickslotKeyMappedModified = 0x23A,
		CP_PassiveskillInfoUpdate = 0x23B,
		CP_UpdateClientEnvironment = 0x23C,
		CP_DirectionNodeCollision = 0x23D,
		CP_UserLaserInfoForRemote = 0x23E,
		CP_ReturnTeleportDebuff = 0x23F,
		CP_CheckProcess = 0x240,
		CP_MemoInGameRequest = 0x241,
		CP_EgoEquipGaugeCompleteReturn = 0x242,
		CP_EgoEquipCreateUpgradeItem = 0x243,
		CP_EgoEquipCreateUpgradeItemCostRequest = 0x244,
		CP_EgoEquipTalkRequest = 0x245,
		CP_EgoEquipCheckUpdateItemRequest = 0x246,
		CP_InheritanceInfoRequest = 0x247,
		CP_InheritanceUpgradeRequest = 0x248,
		CP_MirrorReadingSelectBookRequest = 0x249,
		CP_LikePoint = 0x24A,
		CP_User10thStreamingURLRequest = 0x24B,
		CP_UserUpdateMapleTVShowTime = 0x24C,
		CP_ReduceDotDamgeBaseBuffRequest = 0x24D,
		CP_MirrorStudyComplete = 0x24E,
		CP_RequestArrowPlaterObj = 0x24F,
		CP_UserTimeEventUIOpenRequest = 0x250,
		CP_UserTimeEventResultRequest = 0x251,
		CP_UserTimeEventCompleteRequest = 0x252,
		CP_UserTimeEventPassedTimeSet = 0x253,
		CP_InvasionSettingRequest = 0x254,
		CP_UserFieldAttackObjRequestBoarding = 0x255,
		CP_UserFieldAttackObjRequestGetOff = 0x256,
		CP_MonsterBattle = 0x257,
		CP_BossArenaMatchRequest = 0x258,
		CP_BossArenaMigrateRequest = 0x259,
		CP_MobUserControlSkillQPush = 0x25A,
		CP_MobUserControlSkillQPop = 0x25B,
		CP_MobUserControlSkillForcedQPop = 0x25C,
		CP_PartyQuestRankingRequest = 0x25D,
		CP_AttendanceEvent = 0x25E,
		CP_AttendanceEventRewardReq = 0x25F,
		CP_UIAttendanceGhostChangeReq = 0x260,
		CP_EventUIReq = 0x261,
		CP_AttendanceEventSelectReward = 0x262,
		CP_UserSetCustomizeEffect = 0x263,
		CP_UserCustomizeEffectItemModify = 0x264,
		CP_UserGrowthHelperRequest = 0x265,
		CP_UserContentsMapRequest = 0x266,
		CP_UserTimerReq = 0x267,
		CP_UaerMannequin = 0x268,
		CP_UserBufferFlyReq = 0x269,
		CP_UserNonTargetForceAtomAttack = 0x26A,
		CP_UserRunScript = 0x26B,
		CP_CheckBossPartyByScript = 0x26C,
		CP_SetGoToShineCityWaitField = 0x26D,
		CP_SetStarplanetMiniGameCustomizingOption = 0x26E,
		CP_StarPlanetTrendShopSetAvatar = 0x26F,
		CP_StarPlanetTrendShopRestoreAvatar = 0x270,
		CP_StarPlanetRequest = 0x271,
		CP_StarPlanetMatchingReentrance = 0x272,
		CP_StarPlanetResultUIExitScript = 0x273,
		CP_MoveToUrusWaitingField = 0x274,
		CP_MonsterCollecion_CompleteReward_Req = 0x275,
		CP_MonsterCollecion_Explore_Req = 0x276,
		CP_PlatFormarEnterRequest = 0x277,
		CP_StigmaDeleveryRequest = 0x278,

		CP_BEGIN_EVENT_GROUP = 0x279,
		CP_InvitationAcceptUser = 0x27A,
		CP_InvitationCancleUser = 0x27B,
		CP_EventGroupLeave = 0x27C,

		CP_BEGIN_EVENT_GROUP_PACKET = 0x27D,

		CP_END_EVENT_GROUP_PACKET = 0x27E,

		CP_END_EVENT_GROUP = 0x27F,

		CP_BEGIN_EVENT_RANKING = 0x280,
		CP_EventRankingOpen = 0x281,
		CP_EventRankingHelp = 0x282,
		CP_END_EVENT_RANKING = 0x283,

		CP_BEGIN_AFREECATV = 0x284,
		CP_AfreecaTvBroadStart = 0x285,
		CP_AfreecaTvBroadStop = 0x286,
		CP_END_AFREECATV = 0x287,

		CP_BEGIN_STARPLANET_MATCHING = 0x288,
		CP_StarPlanetMatching_RegisterReq = 0x289,
		CP_StarPlanetMatching_UnRegisterReq = 0x28A,
		CP_StarPlanetMatching_RegisterPartyReq = 0x28B,
		CP_StarPlanetMatching_JoinPartyPlayReq = 0x28C,
		CP_StarPlanetMatching_TransferAssent = 0x28D,
		CP_StarPlanetMatching_HelpScript = 0x28E,
		CP_END_STARPLANET_MATCHING = 0x28F,

		CP_BEGIN_STARPLANET_QUEUE = 0x290,
		CP_StarPlanetQueue_RegisterReq = 0x291,
		CP_StarPlanetQueue_UnRegisterReq = 0x292,
		CP_END_STARPLANET_QUEUE = 0x293,

		CP_BEGIN_STARPLANET_INVITATION = 0x294,
		CP_StarPlanetInvitation_Accept = 0x295,
		CP_StarPlanetInvitation_Cancle = 0x296,
		CP_END_STARPLANET_INVITATION = 0x297,

		CP_UserSurveyRequest = 0x298,
		CP_NPSInfo = 0x299,
		CP_UserFlameOrbRequest = 0x29A,
		CP_User_SADResultUI_Close = 0x29B,
		CP_FreeLookChangeRequest = 0x29C,
		CP_FreeLookChangeUIOpenFailed = 0x29D,
		CP_UserSmartPhoneCallRequest = 0x29E,
		CP_UserJaguarChangeRequest = 0x29F,
		CP_FPSLog = 0x2A0,
		CP_PacketModifyLog = 0x2A1,
		CP_BattleUserAvatarSelect = 0x2A2,
		CP_BattleUserAttack = 0x2A3,
		CP_BattleUserAttackExpire = 0x2A4,
		CP_BattleUserAttackPosition = 0x2A5,
		CP_BattleUserHit = 0x2A6,
		CP_BattleUserHitByMob = 0x2A7,
		CP_BattleStatCoreRequest = 0x2A8,
		CP_BattleUserAlive = 0x2A9,
		CP_UserContentsBookRequest = 0x2AA,
		CP_PerformanceClientLogin = 0x2AB,
		CP_PerformanceClientInField = 0x2AC,
		CP_PingCheckRequest_ClientToGame = 0x2AD,
		CP_Ping_ClientToGame = 0x2AE,
		CP_PlantPotClick = 0x2AF,
		CP_RandomMissionRequest = 0x2B0,
		CP_ItemCollection_SetFlag = 0x2B1,
		CP_ItemCollection_CheckComplete = 0x2B2,
		CP_SelfStatChangeRequest = 0x2B3,
		CP_CashBuffEventCancle = 0x2B4,
		CP_CreatePsychicLock = 0x2B5,
		CP_ResetPathPsychicLock = 0x2B6,
		CP_ReleasePsychicLock = 0x2B7,
		CP_ReserveDamagePsychicLock = 0x2B8,
		CP_CreateKinesisPsychicArea = 0x2B9,
		CP_DoActivePsychicArea = 0x2BA,
		CP_DebuffPsychicArea = 0x2BB,
		CP_ReleasePsychicArea = 0x2BC,
		CP_PsychicOverRequest = 0x2BD,
		CP_DecPsychicPointRequest = 0x2BE,
		CP_TouchMeEndRequest = 0x2BF,
		CP_BiteAttackResponse = 0x2C0,
		CP_SaveUrusSkill = 0x2C1,
		CP_GetSavedUrusSkill = 0x2C2,
		CP_UrusShopRequest = 0x2C3,
		CP_UrusPartyMemberList = 0x2C4,
		CP_UserKeyDownStepRequest = 0x2C5,
		CP_DailyGiftRequest = 0x2C6,
		CP_SkillCommandLock = 0x2C7,
		CP_BeastFormWingOnOff = 0x2C8,
		CP_ResetAirHitCountRequest = 0x2C9,
		CP_RWActionCancel = 0x2CA,
		CP_ReleaseRWGrab = 0x2CB,
		CP_RWClearCurrentAttackRequest = 0x2CC,
		CP_RWMultiChargeCancelRequest = 0x2CD,
		CP_FuntionFootholdMan = 0x2CE,
		CP_END_USER = 0x2CF,

		CP_BEGIN_FIELD = 0x2D0,

		CP_BEGIN_LIFEPOOL = 0x2D1,

		CP_BEGIN_MOB = 0x368, //0x2D2,
		CP_MobMove,// 0x2D3,
		CP_MobApplyCtrl, // = 0x2D4,
		CP_MobDropPickUpRequest,// = 0x2D5,
		CP_MobHitByObstacle,// = 0x2D6,
		CP_MobHitByObstacleAtom,// = 0x2D7,
		CP_MobHitByMob,// = 0x2D8,
		CP_MobSelfDestruct,// = 0x2D9,
		CP_MobSelfDestructCollisionGroup,// = 0x2DA,
		CP_MobAttackMob,// = 0x2DB,
		CP_MobSkillDelayEnd,// = 0x2DC,
		CP_MobTimeBombEnd,// = 0x2DD,
		CP_MobEscortCollision,// = 0x2DE,
		CP_MobRequestEscortInfo,// = 0x2DF,
		CP_MobEscortStopEndRequest,// = 0x2E0,
		CP_MobAreaAttackDisease,// = 0x2E1,
		CP_MobExplosionStart,// = 0x2E2,
		CP_MobLiftingEnd,// = 0x2E3,
		CP_MobUpdateFixedMoveDir,// = 0x2E4,
		CP_MobCreateFireWalk,// = 0x2E5,
		CP_MobAfterDeadRequest,// = 0x2E6,
		CP_MobDamageShareInfo,// = 0x2E7,
		CP_MobCreateAffectedArea,// = 0x2E8,
		CP_MobDownResponse,// = 0x2E9,
		CP_MobUnk1,
		CP_MobUnk2,
		CP_END_MOB,// = 0x2EA,

		CP_BEGIN_NPC,// = 0x2EB,
		CP_NpcMove,//0x2EC,
		CP_NpcSpecialAction,// = 0x2ED,
		CP_END_NPC,// = 0x2EE,

		CP_END_LIFEPOOL,// = 0x2EF,

		CP_BEGIN_DROPPOOL,// = 0x2F0,
		CP_DropPickUpRequest,// = 0x2F1,
		CP_END_DROPPOOL,// = 0x2F2,

		CP_BEGIN_REACTORPOOL,// = 0x2F3,
		CP_ReactorHit,// = 0x2F4,
		CP_ReactorClick,// = 0x2F5,
		CP_ReactorRectInMob,// = 0x2F6,
		CP_ReactorOnKey,// = 0x2F7,
		CP_END_REACTORPOOL,// = 0x2F8,

		CP_BEGIN_FISHINGZONEPOOL,// = 0x2F9,
		CP_FishingInfo,// = 0x2FA,
		CP_FishingEnd,// = 0x2FB,
		CP_END_FISHINGZONEPOOL,// = 0x2FC,

		CP_BEGIN_PERSONAL_OBJECT,// = 0x2FD,
		CP_DecomposerRequest,// = 0x2FE,
		CP_END_PERSONAL_OBJECT,// = 0x2FF,

		CP_BEGIN_EVENT_FIELD = 0x300,
		CP_EventStart = 0x301,
		CP_SnowBallHit = 0x302,
		CP_SnowBallTouch = 0x303,
		CP_CoconutHit = 0x304,
		CP_TournamentMatchTable = 0x305,
		CP_PulleyHit = 0x306,
		CP_END_EVENT_FIELD = 0x307,

		CP_BEGIN_MONSTER_CARNIVAL_FIELD = 0x308,
		CP_MCarnivalRequest = 0x309,
		CP_END_MONSTER_CARNIVAL_FIELD = 0x30A,

		CP_BEGIN_DEFENSE_FIELD = 0x30B,
		CP_DefenseGameRequest = 0x30C,
		CP_END_DEFENSE_FIELD = 0x30D,

		CP_CONTISTATE = 0x30E,

		CP_BEGIN_PARTY_MATCH = 0x30F,
		CP_INVITE_PARTY_MATCH = 0x310,
		CP_CANCEL_INVITE_PARTY_MATCH = 0x311,
		CP_PartyMemberCandidateRequest = 0x312,
		CP_UrusPartyMemberCandidateRequest = 0x313,
		CP_PartyCandidateRequest = 0x314,
		CP_IntrusionFriendCandidateRequest = 0x315,
		CP_IntrusionLobbyCandidateRequest = 0x316,
		CP_END_PARTY_MATCH = 0x317,

		CP_RequestFootHoldMove = 0x318,
		CP_GatherRequest = 0x319,
		CP_GatherEndNotice = 0x31A,
		CP_ActChangeReactorUseRequst = 0x31B,
		CP_UserAntiMacroBombRequest = 0x31C,
		CP_MakeEnterFieldPacketForQuickMove = 0x31D,
		CP_RuneStoneUseReq = 0x31E,
		CP_RuneStoneSkillReq = 0x31F,
		CP_ObtacleAtomCollision = 0x320,
		CP_TimerGaugeTimeout = 0x321,
		CP_FallingCatcherHackCheck = 0x322,
		CP_CookGameRequest = 0x323,
		CP_FPSModeExitRequest = 0x324,
		CP_MakeEnterFieldPacketForMirrorDungeon = 0x325,
		CP_LeaveMirrorDungeon = 0x326,

		CP_BEGIN_RHYTHMGAME = 0x327,
		CP_RhythmGame_HitNote = 0x328,
		CP_RhythmGame_StartRegion = 0x329,
		CP_RhythmGame_EndRegion = 0x32A,
		CP_RhythmGame_EndSpecialAttack = 0x32B,
		CP_RhythmGame_SelectMode = 0x32C,
		CP_RhythmGame_AttackRequest = 0x32D,
		CP_RhythmGame_NpcActionRequest = 0x32E,
		CP_RhythmGame_ExitGame = 0x32F,
		CP_END_RHYTHMGAME = 0x330,

		CP_BEGIN_MOUNTAINRIDING = 0x331,
		CP_MountainRidingHpInfo = 0x332,
		CP_MountainRidingMobInfo = 0x333,
		CP_END_MOUNTAINRIDING = 0x334,

		CP_BEGIN_PIRANHA = 0x335,
		CP_PiranhaInfo = 0x336,
		CP_PiranhaDie = 0x337,
		CP_PiranhaDamage = 0x338,
		CP_PiranhaPrepare = 0x339,
		CP_END_PIRANHA = 0x33A,

		CP_BEGIN_ROBBINS = 0x33B,
		CP_Robbins_IncBomb = 0x33C,
		CP_Robbins_DecBomb = 0x33D,
		CP_Robbins_TossBomb = 0x33E,
		CP_END_ROBBINS = 0x33F,

		CP_BEGIN_FALLINGSTONE = 0x340,
		CP_FallingStoneInfo = 0x341,
		CP_FallingStoneHpInfo = 0x342,
		CP_FallingStonePrepare = 0x343,
		CP_END_FALLINGSTONE = 0x344,

		CP_BEGIN_BATTLEFIELD = 0x345,
		CP_BattleFieldDamage = 0x346,
		CP_BattleFieldSheepRevivalReq = 0x347,
		CP_BattleFieldSheepRevive = 0x348,
		CP_END_BATTLEFIELD = 0x349,

		CP_BEGIN_BOSSARENA = 0x34A,
		CP_BossArenaSelectBoss = 0x34B,
		CP_BossArenaSelectSkill = 0x34C,
		CP_BossArenaSelectDifficulty = 0x34D,
		CP_BossArenaSelectConfirm = 0x34E,
		CP_END_BOSSARENA = 0x34F,

		CP_BEGIN_CATAPULT = 0x350,
		CP_Catapult_UpgradeSkill = 0x351,
		CP_END_CATAPULT = 0x352,

		CP_FieldAttackObjPushAct = 0x353,
		CP_FieldRespawn = 0x354,

		CP_BEGIN_SOUL_DUNGEON = 0x355,
		CP_SoulItemUse = 0x356,
		CP_SoulItemUseVote = 0x357,
		CP_SoulDungeon_Summon_SoulBoss = 0x358,
		CP_END_SOUL_DUNGEON = 0x359,

		CP_BEGIN_SPACEMOONRABBIT = 0x35A,
		CP_SpaceMoonRabbitHitEff = 0x35B,
		CP_SpaceMoonRabbitDamage = 0x35C,
		CP_END_SPACEMOONRABBIT = 0x35D,

		CP_BEGIN_HUNDREDBINGO = 0x35E,
		CP_HBingoCheckNumber = 0x35F,
		CP_HBingoCheckBingo = 0x360,
		CP_END_HUNDREDBINGO = 0x361,

		CP_BEGIN_TYPINGGAME = 0x362,
		CP_TypingGameCheckMsg = 0x363,
		CP_TypingGameWordMobAttack = 0x364,
		CP_TypingGameLevelSelect = 0x365,
		CP_TypingGameSkillAttack = 0x366,
		CP_TypingGameFieldOut = 0x367,
		CP_END_TYPINGGAME = 0x368,

		CP_BEGIN_HUNDREDOXQUIZ = 0x369,
		CP_HOxQuizSelected = 0x36A,
		CP_END_HUNDREDOXQUIZ = 0x36B,

		CP_BEGIN_STARPLANETRPS = 0x36C,
		CP_SPRpsGameUserSelect = 0x36D,
		CP_SPRpsGameAnswer = 0x36E,
		CP_SPRpsGameLeave = 0x36F,
		CP_END_STARPLANETRPS = 0x370,

		CP_BEGIN_SIDESCROLLFLYSHOOTING = 0x371,
		CP_SSFSHitUser = 0x372,
		CP_SSFSLethalAttack = 0x373,
		CP_SSFSExit = 0x374,
		CP_END_SIDESCROLLFLYSHOOTING = 0x375,
		CP_BEGIN_FIELDSTATE = 0x376,
		CP_StarPlanet_HBingoCheckNumber = 0x377,
		CP_StarPlanet_HBingoCheckBingo = 0x378,
		CP_StarPlanet_HBingoSendNumber = 0x379,
		CP_StarPlanet_HRpsSelected = 0x37A,
		CP_StarPlanet_GroupDanceSelected = 0x37B,
		CP_StarPlanet_GroupDanceCancel = 0x37C,
		CP_END_FIELDSTATE = 0x37D,
		CP_BEGIN_MOMENTSWIMAREA = 0x37E,
		CP_MomentSwimArea_WaterLevel = 0x37F,
		CP_END_MOMENTSWIMAREA = 0x380,
		CP_BEGIN_GHOSTPARK = 0x381,
		CP_GhostParkUseRuneReq = 0x382,
		CP_GhostParkRuneHealReq = 0x383,
		CP_GhostParkHitBullet = 0x384,
		CP_END_GHOSTPARK = 0x385,
		CP_BEGIN_FIELD_URUS = 0x386,
		CP_UrusSaveDeadlyUser = 0x387,
		CP_END_FIELD_URUS = 0x388,
		CP_FieldSkillUseRequest = 0x389,
		CP_FieldWeather_Msg = 0x38A,
		CP_FieldStatQRExDay = 0x38B,
		CP_BEGIN_POLOFRITOBOUNTYHUNTING = 0x38C,
		CP_PoloFritoBountyHuntingRequest = 0x38D,
		CP_END_POLOFRITOBOUNTYHUNTING = 0x38E,
		CP_BEGIN_POLOFRITOTOWNDEFENSE = 0x38F,
		CP_PoloFritoTownDefenseRequest = 0x390,
		CP_END_POLOFRITOTOWNDEFENSE = 0x391,
		CP_BEGIN_POLOFRITOCOURTSHIPDANCE = 0x392,
		CP_PoloFritoCourtshipDanceResult = 0x393,
		CP_END_POLOFRITOCOURTSHIPDANCE = 0x394,
		CP_BEGIN_BOSS_DEMIAN_FLYINGSWORD = 0x395,
		CP_DemianObjectMakeEnterAck = 0x396,
		CP_DemianObjectNodeEnd = 0x397,
		CP_DemianObjectErr_Recreate = 0x398,
		CP_END_BOSS_DEMIAN_FLYINGSWORD = 0x399,
		CP_END_FIELD = 0x39A,
		CP_BEGIN_CASHSHOP = 0x39B,
		CP_CashShopChargeParamRequest = 0x39C,
		CP_CashShopQueryCashRequest = 0x39D,
		CP_CashShopCashItemRequest = 0x39E,
		CP_CashShopCheckCouponRequest = 0x39F,
		CP_CashShopMemberShopRequest = 0x3A0,
		CP_CashShopGiftMateInfoRequest = 0x3A1,
		CP_CashShopSearchLog = 0x3A2,
		CP_CashShopCoodinationRequest = 0x3A3,
		CP_CashShopCheckMileageRequest = 0x3A4,
		CP_CashShopNaverUsageInfoRequest = 0x3A5,
		CP_MVP_DailyPack_Request = 0x3A6,
		CP_MVP_SpecialPack_Request = 0x3A7,
		CP_END_CASHSHOP = 0x3A8,
		CP_CheckSPWOnCreateNewCharacter = 0x3A9,
		CP_SetSPW = 0x3AA,
		CP_BEGIN_RAISE = 0x3AB,
		CP_RaiseRefesh = 0x3AC,
		CP_RaiseUIState = 0x3AD,
		CP_RaiseIncExp = 0x3AE,
		CP_RaiseAddPiece = 0x3AF,
		CP_END_RAISE = 0x3B0,
		CP_SendMateMail = 0x3B1,
		CP_RequestGuildBoardAuthKey = 0x3B2,
		CP_RequestConsultAuthKey = 0x3B3,
		CP_RequestClassCompetitionAuthKey = 0x3B4,
		CP_RequestWebBoardAuthKey = 0x3B5,
		CP_IronBoxEvent = 0x3B6,
		CP_BEGIN_ITEMUPGRADE = 0x3B7,
		CP_GoldHammerRequest = 0x3B8,
		CP_GoldHammerComplete = 0x3B9,
		CP_END_ITEMUPGRADE = 0x3BA,
		CP_BEGIN_BATTLERECORD = 0x3BB,
		CP_BattleRecordOnOffRequest = 0x3BC,
		CP_BattleRecordSkillDamageLog = 0x3BD,
		CP_END_BATTLERECORD = 0x3BE,

		CP_BEGIN_FARM = 0x3BF,
		CP_InsertFarmObject = 0x3C0,
		CP_DeleteFarmObject = 0x3C1,
		CP_InsertFarmTile = 0x3C2,
		CP_DeleteFarmTile = 0x3C3,
		CP_TransferFarmField = 0x3C4,
		CP_BuyFarmObject = 0x3C5,
		CP_SelFarmObject = 0x3C6,
		CP_MyHouseUpgrade = 0x3C7,
		CP_FarmAdminCommand = 0x3C8,
		CP_RequestQuestComplete = 0x3C9,
		CP_CheckFarmName = 0x3CA,
		CP_RequestInteractObject = 0x3CB,
		CP_RequestConsumeObject = 0x3CC,
		CP_RequestClickNpc = 0x3CD,
		CP_RequestRandomFarm = 0x3CE,
		CP_RequestFarmVisit = 0x3CF,
		CP_RequestAddFarmFriend = 0x3D0,
		CP_FarmInGameFriendRequest = 0x3D1,
		CP_RequestDeleteFarmFriend = 0x3D2,
		CP_RequestAddBlackList = 0x3D3,
		CP_RequestDeleteBlackList = 0x3D4,
		CP_RequestFarmInfoUI = 0x3D5,
		CP_CheckFarmNameByConsume = 0x3D6,
		CP_RequestAutoHarvest = 0x3D7,
		CP_RequestSoulRecharge = 0x3D8,
		CP_RequestTranferFarmByName = 0x3D9,
		CP_MyFarmMonsterRequest = 0x3DA,
		CP_FarmMonsterCombine = 0x3DB,
		CP_FarmMonsterSetNameRequest = 0x3DC,
		CP_FarmMonsterCare = 0x3DD,
		CP_FarmMonsterPlay = 0x3DE,
		CP_FarmMonsterRelease = 0x3DF,
		CP_FarmMonsterSearchRequest = 0x3E0,
		CP_FarmMonsterPosRecode = 0x3E1,
		CP_FarmMonsterLockerRequest = 0x3E2,
		CP_FarmMonsterLifeExtend = 0x3E3,
		CP_PhotoUpdate = 0x3E4,
		CP_PhotoGetRequest = 0x3E5,
		CP_MyHomeSendNoticeRequest = 0x3E6,
		CP_MyHomeLoadMainLogRequest = 0x3E7,
		CP_MyHomeDeleteLogRequest = 0x3E8,
		CP_FarmWhisper = 0x3E9,
		CP_FarmGroupMessage = 0x3EA,
		CP_RequestFarmFriendRecommend = 0x3EB,
		CP_FarmRequestInGameInfoSet = 0x3EC,
		CP_FarmRequestInGameInfoMod = 0x3ED,
		CP_RequestFarmFriendInfo = 0x3EE,
		CP_RequestFarmToday = 0x3EF,
		CP_RequestFirstEnterReward = 0x3F0,
		CP_CheckAdminAccountLog = 0x3F1,
		CP_END_FARM = 0x3F2,

		CP_CharacterListRequest = 0x3F3,
		CP_CopyCharacterToTestRequest = 0x3F4,
		CP_NO = 0x3F5,
	};

	enum SERVER_PACKET : short
	{
		#pragma region BEGIN_SOCKET
		LP_BEGIN_SOCKET = 0x0,
		LP_CheckPasswordResult = LP_BEGIN_SOCKET,
		LP_WorldInformation,
		LP_LatestConnectedWorld,
		LP_RecommendWorldMessage,
		LP_SetClientKey,
		LP_SetPhysicalWorldID,
		LP_SelectWorldResult,
		LP_SelectCharacterResult,
		LP_AccountInfoResult,
		LP_CreateMapleAccountResult,
		LP_CheckDuplicatedIDResult,
		LP_CreateNewCharacterResult,
		LP_DeleteCharacterResult,
		LP_ReservedDeleteCharacterResult,
		LP_ReservedDeleteCharacterCancelResult,
		LP_RenameCharacterResult,
		LP_SetCharacterID,
		LP_MigrateCommand,
		LP_AliveReq,
		LP_PingCheckResult_ClientToGame,
		LP_AuthenCodeChanged,
		LP_AuthenMessage,
		LP_SecurityPacket,
		LP_PrivateServerPacket,
		LP_ChangeSPWResult,
		LP_CheckSPWExistResult,
		LP_CheckWebLoginEmailID,
		LP_DeleteCharacterOTPRequest,
		LP_CheckCrcResult,
		LP_AlbaRequestResult,
		LP_NotifyCenterAndGameAreConnected,
		LP_CheckAliveAck,
		LP_SetAutoSelectedWorld,
		LP_WorldInfoForShiningResult,
		LP_CharacterListResult,
		LP_CopyCharacterToTestResult,
		LP_ApplyHotfix,
		LP_CheckSPWResult = 0x32,
		LP_END_SOCKET = LP_CheckSPWResult,
		#pragma endregion

		#pragma region BEGIN_MAP
		LP_BEGIN_MAP = 51,
		LP_SetBackgroundEffect = LP_BEGIN_MAP,
		LP_SetMapTagedObjectVisible,
		LP_SetMapTaggedObjectSmoothVisible,
		LP_SetMapTaggedObjectAnimation,
		LP_SetMapObjectAnimation,
		LP_SetMapObjectVisible,
		LP_SetMapObjectMove,
		LP_SetMapObjectCreateLayer,
		LP_SetSpineBackEffect,
		LP_SetSpineObjectEffect,
		LP_CreateSpineRectEvent,
		LP_RemoveSpineRectEvent,
		LP_SpineRE_AddBackEvent,
		LP_SpineRE_AddObjEvent,
		LP_CreateCameraCtrlZone,
		LP_RemoveCameraCtrlZone,
		LP_MapUnk1,
		LP_ClearBackgroundEffect,
		LP_END_MAP = LP_ClearBackgroundEffect,
		#pragma endregion

		#pragma region CHARACTERDATA
		LP_BEGIN_CHARACTERDATA,
		LP_InventoryOperation = LP_BEGIN_CHARACTERDATA,
		LP_InventoryGrow,
		LP_StatChanged,
		LP_TemporaryStatSet,
		LP_TemporaryStatReset,
		LP_ForcedStatSet,
		LP_ForcedStatReset,
		LP_ChangeSkillRecordResult,
		LP_ChangeStealMemoryResult,
		LP_UserDamageOnFallingCheck,
		LP_PersonalShopBuyCheck,
		LP_MobDropMesoPickup,
		LP_BreakTimeFieldEnter,
		LP_RuneActSuccess,
		LP_ResultStealSkillList,
		LP_SkillUseResult,
		LP_ExclRequest,
		LP_GivePopularityResult,
		LP_Message,
		LP_MemoResult,
		LP_MapTransferResult,
		LP_AntiMacroResult,
		LP_AntiMacroBombResult,
		LP_InitialQuizStart,
		LP_ClaimResult,
		LP_SetClaimSvrAvailableTime,
		LP_ClaimSvrStatusChanged,
		LP_StarPlanetUserCount,
		LP_SetTamingMobInfo,
		LP_QuestClear,
		LP_EntrustedShopCheckResult,
		LP_SkillLearnItemResult,
		LP_SkillResetItemResult,
		LP_AbilityResetItemResult,
		LP_ExpConsumeResetItemResult,
		LP_ExpItemGetResult,
		LP_CharSlotIncItemResult,
		LP_CharRenameItemResult,
		LP_GatherItemResult,
		LP_SortItemResult,
		LP_RemoteShopOpenResult,
		LP_PetDeadMessage,
		LP_CharacterInfo,
		LP_PartyResult,
		LP_PartyMemberCandidateResult,
		LP_UrusPartyMemberCandidateResult,
		LP_PartyCandidateResult,
		LP_UrusPartyResult,
		LP_IntrusionFriendCandidateResult,
		LP_IntrusionLobbyCandidateResult,
		LP_ExpeditionRequest,
		LP_ExpeditionNoti,
		LP_FriendResult,
		LP_StarFriendResult,
		//LP_LoadAccountIDOfCharacterFriendResult,
		LP_GuildRequest,
		LP_GuildResult,
		LP_AllianceResult,
		LP_TownPortal,
		LP_BroadcastMsg,
		LP_AswanTimeTableState,
		LP_IncubatorResult,
		LP_IncubatorHotItemResult,
		LP_ShopScannerResult,
		LP_ShopLinkResult,
		//LP_AuctionResult,
		//LP_AuctionMessage,
		LP_MarriageRequest,
		LP_MarriageResult,
		LP_WeddingGiftResult,
		LP_MarriedPartnerMapTransfer,
		LP_CashPetFoodResult,
		LP_CashPetPickUpOnOffResult,
		LP_CashPetSkillSettingResult,
		LP_CashLookChangeResult,
		LP_CashPetDyeingResult,
		LP_SetWeekEventMessage,
		LP_SetPotionDiscountRate,
		LP_BridleMobCatchFail,
		LP_ImitatedNPCResult,
		LP_ImitatedNPCData,
		LP_JournalAvatar,
		LP_LimitedNPCDisableInfo,
		LP_MonsterBookSetCard,
		LP_MonsterBookSetCover,
		LP_HourChanged,
		LP_MiniMapOnOff,
		LP_ConsultAuthkeyUpdate,
		LP_ClassCompetitionAuthkeyUpdate,
		LP_WebBoardAuthkeyUpdate,
		LP_SessionValue,
		LP_PartyValue,
		LP_FieldSetVariable,
		LP_FieldValue,
		LP_BonusExpRateChanged,
		LP_FamilyChartResult,
		LP_FamilyInfoResult,
		LP_FamilyResult,
		LP_FamilyJoinRequest,
		LP_FamilyJoinRequestResult,
		LP_FamilyJoinAccepted,
		LP_FamilyPrivilegeList,
		LP_FamilyFamousPointIncResult,
		LP_FamilyNotifyLoginOrLogout,
		LP_FamilySetPrivilege,
		LP_FamilySummonRequest,
		LP_NotifyLevelUp,
		LP_NotifyWedding,
		LP_NotifyJobChange,
		LP_SetBuyEquipExt,
		LP_SetPassenserRequest,
		LP_ScriptProgressMessageBySoul,
		LP_ScriptProgressMessage,
		LP_ScriptProgressItemMessage,
		LP_SetStaticScreenMessage,
		LP_OffStaticScreenMessage,
		LP_WeatherEffectNotice,
		LP_WeatherEffectNoticeY,
		LP_ProgressMessageFont,
		LP_DataCRCCheckFailed,
		LP_ShowSlotMessage,
		LP_WildHunterInfo,
		LP_ZeroInfo,
		LP_ZeroWP,
		LP_ZeroInfoSubHP,
		LP_OpenUICreatePremiumAdventurer,
		LP_FieldSetEnterSuccessed,
		LP_ResultInstanceTable,
		LP_CoolTimeSet,
		LP_ItemPotChange,
		LP_ItemCoolTimeChange,
		LP_SetAdDisplayInfo,
		LP_SetAdDisplayStatus,
		LP_SetSonOfLinkedSkillResult,
		LP_200,
		LP_201,
		LP_202,
		LP_SetMapleStyeInfo,
		LP_SetBuyLimitCount,
		LP_ResetBuyLimitcount,
		LP_UpdateUIEventListInfo,
		LP_DojangRanking,
		LP_DefenseGameResponse_Shop,
		LP_DefenseGameResponse_Inventory,
		LP_210,
		LP_ShutdownMessage,
		LP_ResultSetStealSkill,
		LP_SlashCommand,
		LP_StartNavigationRequest,
		LP_FuncKeySetByScript,
		LP_CharacterPotentialSet,
		LP_CharacterPotentialReset,
		LP_CharacterHonorExp,
		LP_AswanStateInfo,
		LP_AswanResult,
		LP_ReadyForRespawn,
		LP_ReadyForRespawnByPoint,
		LP_OpenReadyForRespawnUI,
		LP_CharacterHonorGift,
		LP_CrossHunterCompleteResult,
		LP_CrossHunterShopResult,
		LP_SetCashItemNotice,
		LP_SetSpecialCashItem,
		LP_ShowEventNotice,
		LP_BoardGameResult,
		LP_YutGameResult,
		LP_ValuePackResult,
		LP_UserUseNaviFlyingResult,
		LP_MapleStyleResult,
		LP_OpenWeddingEx,
		LP_BingoResult,
		LP_BingoCassandraResult,
		LP_UpdateVIPGrade,
		LP_MesoRangerResult,
		LP_SetMaplePoint,
		LP_SetAdditionalCashInfo,
		LP_SetMiracleTime,
		LP_HyperSkillResetResult,
		LP_GetServerTime,
		LP_GetCharacterPosition,
		LP_246,
		LP_SetFixDamageForTest,
		LP_248,
		LP_ReturnEffectConfirm,
		LP_ReturnEffectModified,
		LP_WhiteAdditionalCubeResult,
		LP_BlackCubeResult,
		LP_MemorialCubeResult,
		LP_MemorialCubeModified,
		LP_DressUpInfoModified,
		LP_256,
		LP_ResetOnStateForOnOffSkill,
		LP_SetOffStateForOnOffSkill,
		LP_IssueReloginCookie,
		LP_AvatarPackTest,
		LP_EvolvingResult,
		LP_ActionBarResult,
		LP_GuildContentResult,
		LP_GuildSearchResult,
		LP_BufferFlyResult,
		LP_HalloweenCandyRankingResult,
		LP_GetRewardResult,
		LP_Mentoring,
		LP_GetLotteryResult,
		LP_CheckProcess,
		LP_CompleteNpcSpeechSuccess,
		LP_CompleteSpecialCheckSuccess,
		LP_SetAccountInfo,
		LP_SetGachaponFeverTime,
		LP_AvatarMegaphoneRes,
		LP_AvatarMegaphoneUpdateMessage,
		LP_AvatarMegaphoneClearMessage,
		LP_RequestEventList,
		LP_LikePoint,
		LP_SignErrorAck,
		LP_AskAfterErrorAck,
		LP_EventNameTagInfo,
		LP_GiveEventNameTag,
		LP_JobFreeChangeResult,
		LP_EventLotteryOpen,
		LP_EventLotteryResult,
		LP_InvasionSupportSet,
		LP_InvasionSupportAttackResult,
		LP_InvasionSupportBossKill,
		LP_InvasionSupportSetttingResult,
		LP_InvasionElapsedTime,
		LP_InvasionSystemMsg,
		LP_InvasionBossKeyChange,
		LP_ScreenMsg,
		LP_TradeBlockForSnapshot,
		LP_LimitGoodsNoticeResult,
		LP_MonsterBattle,
		LP_MonsterBattleCombat,
		LP_UniverseBossPossible,
		LP_UniverseBossImpossible,
		LP_CashShopPreviewInfo,
		LP_ChangeSoulCollectionResult,
		LP_SelectSoulCollectionResult,
		LP_UserMasterPieceResult,
		LP_PendantSlotIncResult,
		LP_BossArenaMatchSucess,
		LP_BossArenaMatchFail,
		LP_BossArenaMatchRequestDone,
		LP_UserSoulMatching,
		LP_Catapult_UpgradeSkill,
		LP_Catapult_ResetSkill,
		LP_PartyQuestRankingResult,
		LP_CoordinationContestInfo,
		LP_WorldTransferResult,
		LP_TrunkSlotIncItemResult,
		LP_EliteMobWorldMapNotice,
		LP_RandomPortalWorldMapNotice,
		LP_WorldTransferHelperNotify,
		LP_EquipmentEnchantDisplay,
		LP_TopTowerRankResult,
		LP_FriendTowerRankResult,
		LP_TowerResultUIOpen,
		LP_MannequinResult,
		LP_IronBoxEvent,
		LP_CreateKoreanJumpingGame,
		LP_326,
		LP_CreateSwingGame,
		LP_UserUpdateMapleTVShowTime,
		LP_ReturnToTitle,
		LP_ReturnToCharacterSelect,
		LP_FlameWizardFlameWalkEffect,
		LP_FlameWizardFlareBlink,
		LP_SummonedAvatarSync,


		LP_CashShopEventInfo = 380,
		LP_BlackList,
		LP_UIOpenTest,
		LP_BlackListView,
		LP_ScrollUpgradeFeverTime,
		LP_TextEquipInfo,
		LP_TextEquipUIOpen,
		LP_UIStarPlanetMiniGameResult,
		LP_UIStarPlanetTrendShop,
		LP_UIStarPlanetQueue,
		LP_UIStarPlanetQueueErr,
		LP_StarPlanetRoundInfo,
		LP_StarPlanetResult,
		LP_BackSpeedCtrl,
		LP_SetMazeArea,
		LP_CharacterBurning,
		LP_BattleStatCoreInfo,
		LP_BattleStatCoreAck,
		LP_GachaponRewardTestResult,
		LP_MasterPieceTestRewardResult,
		LP_RoyalStyleTestRewardResult,
		LP_BeautyCouponTestRewardResult,
		LP_NickSkillExpired,
		LP_RandomMissionResult,
		LP_12TresureResult,
		LP_12TresureJumpHigh,
		LP_ItemCollection_SetFlag,
		LP_ItemCollection_CheckComplete,
		LP_ItemCollection_SendCollectionList,
		LP_ToadsHammerRequestResult,
		LP_HyperStatSkillResetResult,
		LP_InventoryOperationResult,
		LP_GetSavedUrusSkill,
		LP_SetRolePlayingCharacterInfo,
		LP_MVP_Alarm,
		LP_MonsterCollecion_CompleteReward_Result,
		LP_UserTowerChairSettingResult,
		LP_NeedClientResponse,
		LP_CharacterModified,
		LP_419,
		LP_TradeKingShopItem,
		LP_TradeKingShopRes,
		LP_PlatFormarEnterResult,
		LP_PlatFormar_Oxyzen,


		LP_MacroSysDataInit = 0x1BE,
		LP_END_CHARACTERDATA = LP_MacroSysDataInit,
#pragma endregion

		#pragma region STAGE
		LP_BEGIN_STAGE,
		LP_SetField = LP_BEGIN_STAGE,
		LP_SetFarmField,
		LP_MTS,
		LP_MTSInfo,
		LP_SetCashShop,
		LP_SetCashShopInfo,
		LP_END_STAGE = LP_SetCashShopInfo,
#pragma endregion

		#pragma region FIELD
		LP_BEGIN_FIELD,
		LP_TransferFieldReqIgnored = LP_BEGIN_FIELD,
		LP_TransferChannelReqIgnored,
		LP_TransferPvpReqIgnored,
		LP_FieldSpecificData,
		LP_GroupMessage,
		LP_FieldUniverseMessage,
		LP_Whisper,
		LP_MobSummonItemUseResult,
		LP_FieldEffect,
		LP_BlowWeather,
		LP_PlayJukeBox,
		LP_AdminResult,
		LP_Quiz,
		LP_Desc,
		LP_Clock,
		LP_CONTIMOVE,
		LP_CONTISTATE,
		LP_SetQuestClear,
		LP_SetQuestTime,
		LP_SetObjectState,
		LP_DestroyClock,
		LP_ShowArenaResult,
		LP_StalkResult,
		LP_MassacreIncGauge,
		LP_MassacreResult,
		LP_QuickslotMappedInit,
		LP_FootHoldMove,
		LP_CorrectFootHoldMove,
		LP_DynamicObjMove,
		LP_DynamicObjShowHide,
		LP_DynamicObjUrusSync,
		LP_FieldKillCount,
		LP_SmartMobNoticeMsg,
		LP_MobPhaseChange,
		LP_MobZoneChange,
		LP_MobOrderFromSvr,
		LP_PvPStatusResult,
		LP_InGameCurNodeEventEnd,
		LP_ForceAtomCreate,
		LP_SetAchieveRate,
		LP_SetQuickMoveInfo,
		LP_ChangeAswanSiegeWeaponGauge,
		LP_ObtacleAtomCreate,
		LP_ObtacleAtomClear,
		LP_Box2dFootHoldCreate,
		LP_DebuffObjOn,
		LP_FieldCreateFallingCatcher,
		LP_MobChaseEffectSet,
		LP_MesoExchangeResult,
		LP_SetMirrorDungeonInfo,
		LP_SetIntrusion,
		LP_CannotDropForTradeBlock,
		LP_FootHoldOnOff,
		LP_LadderRopeOnOff,
		LP_MomentAreaOnOff,
		LP_MomentAreaOnOffAll,
		LP_ChatLetClientConnect,
		LP_ChatInduceClientConnect,
		LP_CoordinationContestResult,
		LP_EliteState,
		LP_PlaySound,
		LP_StackEventGauge,
		LP_SetUnionField,
		LP_MTalkOfflineAccountFriendsNameResult,
		LP_StarPlanetBurningTimeInfo,
		LP_PublicShareStateValue,
		LP_FunctionTempBlock,
		LP_StatusBar,
		LP_FieldSkillDelay,
		LP_FieldWeather_Add,
		LP_FieldWeather_Remove,
		LP_FieldWeather_Msg,
		LP_ADD_WRECKAGE,
		LP_DEL_WRECKAGE,
		LP_CreateMirrorImage,
		LP_FuntionFootholdMan,

		#pragma region USERPOOL

		LP_BEGIN_USERPOOL = 0x21C,
		LP_UserEnterField = LP_BEGIN_USERPOOL,
		LP_UserLeaveField,

		#pragma region USERCOMMON
		LP_BEGIN_USERCOMMON,
		LP_UserChat = LP_BEGIN_USERCOMMON,
		LP_UserADBoard,
		LP_UserMiniRoomBalloon,
		LP_UserConsumeItemEffect,
		LP_UserItemUpgradeEffect,
		LP_UserItemEventUpgradeEffect,
		LP_UserItemSkillSocketUpgradeEffect,
		LP_UserItemSkillOptionUpgradeEffect,
		LP_UserItemReleaseEffect,
		LP_UserItemUnreleaseEffect,
		LP_UserItemLuckyItemEffect,
		LP_UserItemMemorialCubeEffect,
		LP_UserItemAdditionalUnReleaseEffect,
		LP_UserItemAdditionalSlotExtendEffect,
		LP_UserItemFireWorksEffect,
		LP_UserItemOptionChangeEffect,
		LP_UserItemRedCubeResult,
		LP_UserHitByUser,
		LP_UserDotByUser,
		LP_UserResetAllDot,
		LP_UserDamageByUser,
		LP_UserTeslaTriangle,
		LP_UserFollowCharacter,
		LP_UserShowPQReward,
		LP_UserSetOneTimeAction,
		LP_UserMakingSkillResult,
		LP_UserMakingMeisterSkillEff,
		LP_UserGatherResult,
		LP_UserExplode,
		LP_UserHitByCounter,
		LP_PyramidLethalAttack,
		LP_UserMixerResult,
		LP_UserWaitQueueReponse,
		LP_UserCategoryEventNameTag,
		LP_UserSetDamageSkin,
		LP_UserSetDamageSkin_Premium,
		LP_UserSoulEffect,
		LP_UserSitResult,
		LP_UserStarPlanetPointInfo,
		LP_UserStarPlanetAvatarLookSet,
		LP_UserTossedBySkill,
		LP_UserBattleAttackHit,
		LP_UserBattleUserHitByMob,
		LP_UserFreezeHotEventInfo,
		LP_UserEventBestFriendInfo,
		LP_UserSetReapeatOneTimeAction,
		LP_UserSetReplaceMoveAction,
		LP_UserItemInGameCubeResult,
		LP_UserBattlePvPTemporaryStat,
		LP_UserSetActiveEmoticonItem,
		LP_UserCreatePsychicLock,
		LP_UserRecreatePathPsychicLock,
		LP_UserReleasePsychicLock,
		LP_UserReleasePsychicLockMob,
		LP_UserCreatePsychicArea,
		LP_UserReleasePsychicArea,
		LP_UserRWZeroBunkerMobBind,
		LP_UserBeastFormWingOnOff,
		LP_UserMesoChairAddMeso,
		LP_UserRefreshNameTagMark,
		LP_UserStigmaEffect,
		#pragma region PET
		LP_BEGIN_PET = 0x26E,
		LP_PetActivated = LP_BEGIN_PET,
		LP_PetMove,
		LP_PetAction,
		LP_PetActionSpeak,
		LP_PetNameChanged,
		LP_627,
		LP_PetLoadExceptionList,
		LP_PetHueChanged,
		LP_630,
		LP_PetModified,
		LP_PetActionCommand,
		LP_END_PET = LP_PetActionCommand,
		#pragma endregion

		#pragma region DRAGON
		LP_BEGIN_DRAGON,
		LP_DragonEnterField = LP_BEGIN_DRAGON,
		LP_DragonMove,
		LP_DragonVanish_Script,
		LP_DragonLeaveField,
		LP_END_DRAGON = LP_DragonLeaveField,
		#pragma endregion

		#pragma region ANDROID
		LP_BEGIN_ANDROID,
		LP_AndroidEnterField = LP_BEGIN_ANDROID,
		LP_AndroidMove,
		LP_AndroidActionSet,
		LP_AndroidModified,
		LP_AndroidLeaveField,
		LP_END_ANDROID = LP_AndroidLeaveField,
		#pragma endregion

		#pragma region FOXMAN
		LP_BEGIN_FOXMAN,
		LP_FoxManEnterField = LP_BEGIN_FOXMAN,
		LP_FoxManMove,
		LP_FoxManExclResult,
		LP_FoxManShowChangeEffect,
		LP_FoxManModified,
		LP_FoxManLeaveField,
		LP_END_FOXMAN = LP_FoxManLeaveField,
		#pragma endregion

		#pragma region SKILLPET
		LP_BEGIN_SKILLPET,
		LP_SkillPetMove,
		LP_SkillPetAction,
		LP_SkillPetState,
		LP_SkillPetNameChanged,
		LP_SkillPetLoadExceptionList,
		LP_SkillPetTransferField,
		LP_END_SKILLPET,
		#pragma endregion

		LP_656,

		#pragma region Unk
		LP_657,
		LP_658,
		LP_659,
		#pragma endregion

		LP_END_USERCOMMON,
		#pragma endregion

		#pragma region USERREOMTE
		LP_BEGIN_USERREMOTE,
		LP_UserMove = LP_BEGIN_USERREMOTE,
		LP_UserMeleeAttack,
		LP_UserShootAttack,
		LP_UserMagicAttack,
		LP_UserBodyAttack,
		LP_UserSkillPrepare,
		LP_UserMovingShootAttackPrepare,
		LP_UserSkillCancel,
		LP_UserHit,
		LP_UserEmotion,
		LP_AndroidEmotion,
		LP_UserSetActiveEffectItem,
		//LP_UserSetActiveMonkeyEffectItem,
		LP_UserSetActiveNickItem,
		LP_UserSetDefaultWingItem,
		LP_UserSetKaiserTransformItem,
		LP_UserSetCustomRiding,
		LP_UserShowUpgradeTombEffect,
		LP_UserSetActivePortableChair,
		LP_UserAvatarModified,
		LP_UserEffectRemote,
		LP_UserTemporaryStatSet,
		LP_UserTemporaryStatReset,
		LP_UserHP,
		LP_UserGuildNameChanged,
		LP_UserGuildMarkChanged,
		LP_UserPvPTeamChanged,
		LP_GatherActionSet,
		LP_UpdatePvPHPTag,
		LP_UserEvanDragonGlide,
		LP_UserKeyDownAreaMove,
		LP_UserLaserInfo,
		LP_UserKaiserColorOrMorphChange,
		LP_UserDestroyGranade,
		LP_UserSetItemAction,
		LP_ZeroTag,
		LP_UserIntrusionEffect,
		LP_ZeroLastAssistState,
		LP_UserSetMoveGrenade,
		LP_UserSetCustomizeEffect,
		LP_RuneStoneActionAck,
		LP_KinesisPsychicEnergyShieldEffect,
		LP_DragonAction,
		LP_DragonBreathEarthEffect,
		LP_ReleaseRWGrab,
		LP_RemoteRWMultiChargeCancel,
		LP_ScouterMaxDamageUpdate,
		LP_UserRemoteStigmaResponse,

		LP_UserThrowGrenade = 0x2CC,
		LP_END_USERREMOTE = LP_UserThrowGrenade,
		#pragma endregion

		#pragma region USERLOCAL
		LP_BEGIN_USERLOCAL,
		LP_UserEmotionLocal = LP_BEGIN_USERLOCAL,
		LP_AndroidEmotionLocal,
		LP_UserEffectLocal,
		LP_UserTeleport,
		LP_Premium,
		LP_MesoGive_Succeeded,
		LP_MesoGive_Failed,
		LP_UserQuestResult,
		LP_NotifyHPDecByField,
		LP_UserPetSkillChanged,
		LP_UserBalloonMsg,
		LP_PlayEventSound,
		LP_PlayMinigameSound,
		LP_UserMakerResult,
		LP_UserOpenConsultBoard,
		LP_UserOpenClassCompetitionPage,
		LP_UserOpenUI,
		LP_UserCloseUI,
		LP_UserOpenUIWithOption,
		LP_UserOpenWebUI,
		LP_SetDirectionMode,
		LP_SetInGameDirectionMode,
		LP_SetStandAloneMode,
		LP_UserHireTutor,
		LP_UserTutorMsg,
		LP_UserHireTutorById,
		LP_UserSetPartner,
		LP_UserSetPartnerAction,
		LP_UserSetPartnerForceFlip,
		LP_UserSwitchRP,
		LP_ModCombo,
		LP_IncComboByComboRecharge,
		LP_SetRadioSchedule,
		LP_UserOpenSkillGuide,
		LP_UserNoticeMsg,
		LP_UserChatMsg,
		LP_UserSetUtilDlg,
		LP_UserBuffzoneEffect,
		LP_UserTimeBombAttack,
		LP_UserExplosionAttack,
		LP_UserPassiveMove,
		LP_UserFollowCharacterFailed,
		LP_UserRequestExJablin,
		LP_CreateNewCharacterResult_PremiumAdventurer,
		LP_GatherRequestResult,
		LP_RuneStoneUseAck,
		LP_UserBagItemUseResult,
		LP_RandomTeleportKey,
		LP_SetGagePoint,
		LP_UserInGameDirectionEvent,
		LP_MedalReissueResult,
		LP_DodgeSkillReady,
		LP_RemoveMicroBuffSkill,
		LP_UserPlayMovieClip,
		LP_RewardMobListResult,
		LP_IncJudgementStack,
		LP_IncCharmByCashPRMsg,
		LP_SetBuffProtector,
		LP_ChangeLarknessStack,
		LP_DetonateBomb,
		LP_AggroRankInfo,
		LP_DeathCountInfo,
		LP_IndividualDeathCountInfo,
		LP_UserSetDressUpState,
		LP_UserSeverAckMobZoneStateChange,
		LP_SummonEventRank,
		LP_SummonEventReward,
		LP_UserRandomEmotion,
		LP_UserFlipTheCoinEnabled,
		LP_UserTrickOrTreatResult,
		LP_UserGiantPetBuff,
		LP_UserB2BodyResult,
		LP_SetDead,
		LP_OpenUIOnDead,
		LP_EXPIRED_NOTICE,
		LP_UserLotteryItemUIOpen,
		LP_UserRouletteStart,
		LP_UserSitOnTimeCapsule,
		LP_UserSitOnDummyChair,
		LP_UserGoMonsterFarm,
		LP_UserMonsterLifeInviteItemResult,
		LP_PhotoGetResult,
		LP_UserFinalAttackRequest,
		LP_UserSetGun,
		LP_UserSetAmmo,
		LP_UserCreateGun,
		LP_UserClearGun,
		LP_UserShootAttackInFPSMode,
		LP_MirrorDungeonEnterFail,
		LP_MirrorDungeonUnitCleared,
		LP_MirrorDungeonDetail,
		LP_MirrorDungeonRecord,
		LP_UserOpenURL,
		LP_ZeroCombatRecovery,
		LP_MirrorStudyUIOpen,
		LP_SkillCooltimeReduce,
		LP_MirrorReadingUIOpen,
		LP_UserControlMobSkillPushAck,
		LP_ZeroLevelUpAlram,
		LP_UserControlMobSkillPopAck,
		LP_UserControlMobSkillFail,
		LP_SummonedForceRemove,
		LP_UserRespawn,
		LP_UserControlMobSkillForcedPopAck,
		LP_MonsterBattleCapture,
		LP_IsUniverse,
		LP_PortalGroupAck,
		LP_SetMovable,
		LP_UserControlMobSkillPushCoolTime,
		LP_MoveParticleEff,
		LP_UserDoActiveEventSkillByScript,
		LP_SetStatusBarJobNameBlur,
		LP_RuneStoneSkillAck,
		LP_RuneStoneOverTime,
		LP_MoveToContents_CannotMigrate,
		LP_PlayAmbientSound,
		LP_StopAmbientSound,
		LP_FlameWizardElementFlameSummon,
		LP_UserCameraMode,
		LP_SpotlightToCharacter,
		LP_CheckBossPartyByScriptDone,
		LP_FreeLookChangeUIOpen,
		LP_FreeLookChangeSuccess,
		LP_SetGrayBackGround,
		LP_GetNpcCurrentAction,
		LP_CameraRotation,
		LP_CameraSwitch,
		LP_CameraCtrlMsg,
		LP_UserSetFieldFloating,
		LP_AddPopupSay,
		LP_RemovePopupSay,
		LP_JaguarSkill,
		LP_NpcActionLayerRelmove,
		LP_UserClientResolutionRequest,
		LP_UserBonusAttackRequest,
		LP_UserRandAreaAttackRequest,
		LP_JaguarActive,
		LP_SkillCooltimeSetM,
		LP_SetCarryReactorInfo,
		LP_ReactorSkillUseRequest,
		LP_OpenBattlePvPChampSelectUI,
		LP_BattlePvPItemDropSound,
		LP_SetPointForMiniGame,
		LP_PlantPotClickResult,
		LP_PlantPotEffect,
		LP_UserFixDamage,
		LP_RoyalGuardAttack,
		LP_DoActivePsychicArea,
		LP_UserEnterFieldPsychicInfo,
		LP_UserLeaveFieldPsychicInfo,
		LP_TouchMeStateResult,
		LP_UrusFieldScoreUpdate,
		LP_UrusReusltUIOpen,
		LP_UrusNoMoreLife,
		LP_RegisterTeleport,
		LP_UserCreateAreaDotInfo,
		LP_SetSlownDown,
		LP_RegisterExtraSkill,
		LP_ResWarriorLiftMobInfo,
		LP_UserRenameResult,
		LP_UserDamageSkinSaveResult,
		LP_UserLocalStigmaStackDuration,

		LP_SkillCooltimeSet = 0x03AD,
		LP_END_USERLOCAL = LP_SkillCooltimeSet,
		#pragma endregion

		LP_END_USERPOOL,
		#pragma endregion

		#pragma region SUMMONED
		LP_BEGIN_SUMMONED,
		LP_SummonedEnterField = LP_BEGIN_SUMMONED,
		LP_SummonedLeaveField,
		LP_SummonedMove,
		LP_SummonedAttack,
		LP_SummonedAttackPvP,
		LP_SummonedSetReference,
		LP_SummonedSkill,
		LP_SummonedSkillPvP,
		LP_SummonedHPTagUpdate,
		LP_SummonedAttackDone,
		LP_SummonedSetAbleResist,
		LP_SummonedAction,
		LP_SummonedAssistAttackRequest,
		LP_SummonedAttackActive,
		LP_SummonedBeholderRevengeAttack,
		LP_SummonedUnk1,
		LP_SummonedUnk2,
		LP_SummonedHit,
		LP_END_SUMMONED = LP_SummonedHit,
		#pragma endregion

		#pragma region MOBPOOL
		LP_BEGIN_MOBPOOL,
		LP_MobEnterField = LP_BEGIN_MOBPOOL,
		LP_MobLeaveField,
		LP_MobChangeController,
		LP_MobSetAfterAttack,
		LP_MobBlockAttack,
		LP_UrusOnlyMobSkill,
		#pragma region MOB
		LP_BEGIN_MOB,
		LP_MobMove = LP_BEGIN_MOB,
		LP_MobCtrlAck,
		LP_MobCtrlHint,
		LP_MobStatSet,
		LP_MobStatReset,
		LP_MobSuspendReset,
		LP_MobAffected,
		LP_MobDamaged,
		LP_MobUnk1,
		LP_MobUnk2,
		LP_MobSpecialEffectBySkill,
		LP_MobHPChange,
		LP_MobCrcKeyChanged,
		LP_MobCrcDataRequest,
		LP_MobHPIndicator,
		LP_MobCatchEffect,
		LP_MobStealEffect,
		LP_MobEffectByItem,
		LP_MobSpeaking,
		LP_MobMessaging,
		LP_MobSkillDelay,
		LP_MobRequestResultEscortInfo,
		LP_MobEscortStopEndPermmision,
		LP_MobEscortStopByScript,
		LP_MobEscortStopSay,
		LP_MobEscortReturnBefore,
		LP_MobNextAttack,
		LP_MobTeleport,
		LP_MobForcedAction,
		LP_MobForcedSkillAction,
		LP_MobUnk3,
		LP_MobTimeResist,
		LP_MobAllKill,
		LP_MobAttackBlock,
		LP_MobAttackPriority,
		LP_MobAttackTimeInfo,
		LP_MobDamageShareInfoToLocal,
		LP_MobDamageShareInfoToRemote,
		LP_BreakDownTimeZoneTimeOut,
		LP_MoveAreaSet,
		LP_MobDoSkillByHit,
		LP_CastingBarSkill,
		LP_MobFlyTarget,
		LP_BounceAttackSkill,
		LP_MobAffectedAreaByHit,
		LP_MobLtRbDamageSkill,
		LP_MobUnk4,
		LP_MobUnk5,
		LP_MobUnk6,
		LP_MobUnk7,
		LP_MobUnk8,
		LP_MobSummonSubBodySkill,
		LP_MobUnk9,
		LP_MobUnkA,
		LP_MobUnkB,
		LP_MobLaserControl,
		LP_MobScale,
		LP_MobSpecialAction,
		LP_MobPartSystem,
		LP_MobForceChase,
		LP_MobHangOver,
		LP_MobHangOverRelease,
		LP_MobDeadFPSMode,
		LP_MobAirHit,
		LP_MobDemianDelayedAttackCreate,
		LP_RegisterMobZone,
		LP_UnregisterMobZone,
		LP_SetNextTargetFromSvr,
		LP_MobUnkC,
		LP_MobAttackedByMob,
		LP_END_MOB = LP_MobAttackedByMob,
		#pragma endregion
		LP_END_MOBPOOL,
		#pragma endregion

		#pragma region MINIONPOOL
		LP_BEGIN_MINIONPOOL,
		LP_MinionEnterField = LP_BEGIN_MINIONPOOL,
		LP_MinionLeaveField,
		LP_MinionChangeController,
		LP_MinionGenBeyondSplit,
		LP_END_MINIONPOOL = LP_MinionGenBeyondSplit,
		#pragma endregion

		#pragma region NPCPOOL
		LP_BEGIN_NPCPOOL,
		LP_NpcEnterField = LP_BEGIN_NPCPOOL,
		LP_NpcLeaveField,
		LP_NpcEnterFieldForQuickMove,
		LP_NpcChangeController,
		LP_NpcUnk1,

		#pragma region NPC
		LP_BEGIN_NPC,
		LP_NpcMove = LP_BEGIN_NPC,
		LP_NpcUpdateLimitedInfo,
		LP_NpcShowQuizScore,
		LP_NpcShowQuizScoreAni,
		LP_ForceMoveByScript,
		LP_ForceFlipByScript,
		LP_NpcUnk2,
		LP_NpcEmotion,
		LP_NpcCharacterBaseAction,
		LP_NpcViewOrHide,
		LP_NpcPresentItemSet,
		LP_NpcPresentTimeSet,
		LP_NpcSpecialActionReset,
		LP_NpcSetScreenInfo,
		LP_NpcUnk3,
		LP_NpcUnk4,
		LP_NpcLocalRepeatEffect,
		LP_NpcSetNoticeBoardInfo,
		LP_NpcSpecialAction,
		LP_END_NPC = LP_NpcSpecialAction,
		#pragma endregion

		#pragma region NPCTEMPLATE
		LP_BEGIN_NPCTEMPLATE,
		LP_NpcSetScript = LP_BEGIN_NPCTEMPLATE,
		LP_END_NPCTEMPLATE = LP_NpcSetScript,
		#pragma endregion

		LP_END_NPCPOOL,
		#pragma endregion

		#pragma region EMPLOYEEPOOL
		LP_BEGIN_EMPLOYEEPOOL,
		LP_EmployeeEnterField = LP_BEGIN_EMPLOYEEPOOL,
		LP_EmployeeLeaveField,
		LP_EmployeeUnk1,
		LP_EmployeeMiniRoomBalloon,
		LP_END_EMPLOYEEPOOL = LP_EmployeeMiniRoomBalloon,
		#pragma endregion

		#pragma region DROPPOOL
		LP_BEGIN_DROPPOOL,
		LP_DropEnterField = LP_BEGIN_DROPPOOL,
		LP_DropUnk1,
		LP_DropLeaveField,
		LP_END_DROPPOOL = LP_DropLeaveField,
		#pragma endregion

		#pragma region MESSAGEBOXPOOL
		LP_BEGIN_MESSAGEBOXPOOL,
		LP_CreateMessgaeBoxFailed = LP_BEGIN_MESSAGEBOXPOOL,
		LP_MessageBoxEnterField,
		LP_MessageBoxLeaveField,
		LP_END_MESSAGEBOXPOOL = LP_MessageBoxLeaveField,
		#pragma endregion

		#pragma region AFFECTEDAREAPOOL
		LP_BEGIN_AFFECTEDAREAPOOL,
		LP_AffectedAreaCreated = LP_BEGIN_AFFECTEDAREAPOOL,
		LP_MobSkillInstalledFire,
		LP_AffectedAreaRemoved,
		LP_END_AFFECTEDAREAPOOL = LP_AffectedAreaRemoved,
		#pragma endregion

		#pragma region TOWNPORTALPOOL
		LP_BEGIN_TOWNPORTALPOOL,
		LP_TownPortalCreated = LP_BEGIN_TOWNPORTALPOOL,
		LP_TownPortalRemoved,
		LP_END_TOWNPORTALPOOL = LP_TownPortalRemoved,
		#pragma endregion

		#pragma region RANDOMPORTALPOOL
		LP_BEGIN_RANDOMPORTALPOOL,
		LP_RandomPortalCreated = LP_BEGIN_RANDOMPORTALPOOL,
		LP_RandomPortalTryEnterRequest,
		LP_RandomPortalRemoved,
		LP_END_RANDOMPORTALPOOL = LP_RandomPortalRemoved,
		#pragma endregion

		#pragma region OPENGATEPOOL
		LP_BEGIN_OPENGATEPOOL,
		LP_OpenGateCreated = LP_BEGIN_OPENGATEPOOL,
		LP_OpenGateClose,
		LP_OpenGateRemoved,
		LP_END_OPENGATEPOOL = LP_OpenGateRemoved,
		#pragma endregion

		#pragma region REACTORPOOL
		LP_BEGIN_REACTORPOOL,
		LP_ReactorChangeState = LP_BEGIN_REACTORPOOL,
		LP_ReactorMove,
		LP_ReactorEnterField,
		LP_ReactorStateReset,
		LP_ReactorOwnerInfo,
		LP_ReactorRemove,
		LP_ReactorLeaveField,
		LP_END_REACTORPOOL = LP_ReactorLeaveField,
		#pragma endregion

		#pragma region FISHINGZONEPOOL
		LP_BEGIN_FISHINGZONEPOOL,
		LP_FishingInfo = LP_BEGIN_FISHINGZONEPOOL,
		LP_FishingReward,
		LP_FishingZoneInfo,
		LP_END_FISHINGZONEPOOL = LP_FishingZoneInfo,
		#pragma endregion

		#pragma region PERSONAL_MAP_OBJECT
		LP_BEGIN_PERSONAL_MAP_OBJECT,
		LP_DecomposerEnterField = LP_BEGIN_PERSONAL_MAP_OBJECT,
		LP_DecomposerLeaveField,
		LP_END_PERSONAL_MAP_OBJECT = LP_DecomposerLeaveField,
		#pragma endregion

		#pragma region ETCFIELDOBJ
		LP_BEGIN_ETCFIELDOBJ,
		LP_SnowBallState = LP_BEGIN_ETCFIELDOBJ,
		LP_SnowBallHit,
		LP_SnowBallMsg,
		LP_SnowBallTouch,
		LP_CoconutHit,
		LP_CoconutScore,
		LP_HealerMove,
		LP_PulleyStateChange,
		LP_MCarnivalEnter,
		LP_MCarnivalPersonalCP,
		LP_MCarnivalTeamCScore,
		LP_MCarnivalSpellCooltime,
		LP_MCarnivalResultSuccess,
		LP_MCarnivalResultFail,
		LP_MCarnivalDeath,
		LP_MCarnivalMemberOut,
		LP_MCarnivalGameResult,
		LP_MCarnivalUpdateRankInfo,
		LP_ArenaScore,
		LP_BattlefieldEnter,
		LP_BattlefieldScore,
		LP_BattlefieldTeamChanged,
		LP_WitchtowerScore,
		LP_BossSummonTimer = 1124,
		LP_PVPFieldEnter,
		LP_PVPTeamChange,
		LP_PVPModeChange,
		LP_PVPStateChange,
		LP_PVPUpdateCount,
		LP_PVPModeResult,
		LP_PVPUpdateTeamInfo,
		LP_PVPUpdateRankInfo,
		LP_PVPHPChanged,
		LP_PVPTeamScore,
		LP_PVPReviveMessage,
		LP_PVPScreenEffect,
		LP_PVPIceKnightHPChange,
		LP_DefenseWave,
		LP_DefenseLife,
		LP_DefensePoint,
		LP_DefenseScoreRank,
		LP_DefenseResult,
		LP_RandomDropPicked,
		LP_BroadCastRandomDropPicked,
		LP_BroadCastRandomDropPhase,
		LP_RandomDropResult,
		LP_RandomDropPointEffect,
		LP_PVPHardCoreMigrate,
		LP_PVPHardCoreDead,
		LP_PVPHardCoreKill,
		LP_PVPHardcoreGauge,
		LP_PVPHardcoreFieldInfo,
		LP_PVPHardcoreEnter,
		LP_PVPHardcoreFieldChange,
		LP_PVPHardcoreShutDown,
		LP_PVPHardcoreChampionEffect,
		LP_MultiStage_StageSet,
		LP_MultiStage_MobCount,
		LP_Cook_SetRecipes,
		LP_RhythmGameInit,
		LP_RhythmGameUserInfo,
		LP_RhythmGameResult,
		LP_RhythmGameRegionResult,
		LP_RhythmGameSpecialAttackResult,
		LP_RhythmGameAttackEffect,
		LP_RhythmGameSpecialMissionEffect,
		LP_RhythmGameSpecialAttackEffect,
		LP_RhythmGameShowFeverEffect,
		LP_RhythmGameShowLongNoteEffect,
		LP_RhythmGameSpecialMissionSpotEffect,
		LP_RhythmGameInfo,
		LP_MountainRidingHpInfo,
		LP_MountainRidingUIInfo,
		LP_MountainRidingMobInfo,
		LP_RhythmGameUserName,
		LP_FieldRankCreate,
		LP_FieldRankSetUserName,
		LP_FieldRankResult,
		LP_PiranhaInit,
		LP_PiranhaOnOff,
		LP_PiranhaDie,
		LP_FallingStoneInit,
		LP_FallingStoneHpInfo,
		LP_FallingStonePointEffect,
		LP_FallingStoneUserExit,
		LP_BattleFieldSpecialEffect,
		LP_BattleFieldLifeScore,
		LP_BattleFieldSheepMorph,
		LP_BattleFieldDamageEffect,
		LP_BattleFieldSheepRevivalEffect,
		LP_BattleFieldSheepRevivalEnd,
		LP_BattleFieldSheepDead,
		LP_BattleFieldGuidMsg,
		LP_BattleFieldUserInit,
		LP_BossArenaStateChange,
		LP_BossArenaCurrentTeamInfo,
		LP_BossArenaSelectedTeamInfo,
		LP_BossArenaOpponentSelectBoss,
		LP_BossArenaOpponentConfirm,
		LP_HekatonDoSkill,
		LP_HekatonReadySkill,
		LP_HekatonRankingInfo,
		LP_HekatonResult,
		LP_BossArenaScoreInfo,
		LP_BossArenaResultInfo,
		LP_UniverseBossHPInfo,
		LP_BossArenaFadeInOut,
		LP_BossArenaSummonHeadGear,
		LP_BossArenaBossInfo,
		LP_UserHPChangedInBossArena,
		LP_SpaceMoonRabbitFieldInfo,
		LP_SpaceMoonRabbitFieldState,
		LP_SpaceMoonRabbitUserInfoDC,
		LP_SpaceMoonRabbitUserEffect,
		LP_SpaceMoonRabbitAttack,
		LP_SpaceMoonRabbitDamage,
		LP_SpaceMoonRabbitPhase,
		LP_FieldFadeObjectInfo,
		LP_RuneStoneClearAndAllRegister,
		LP_RuneStoneDisappear,
		LP_RuneStoneAppear,
		LP_BonusRewardBoardFAO,
		LP_StarPlanetScreen_WorldEvent,
		LP_FieldState_Create,
		LP_FieldState_Remove,
		LP_FieldChaserMove,
		LP_12thTresureInfoUpdate,
		LP_12thTresureStateChage,
		LP_PoloFritoBountyHuntingStage,
		LP_PoloFritoTownDefenseWave,
		LP_PoloFritoTownDefenseLife,
		LP_PoloFritoCourtshipDanceState,
		LP_PoloFritoCourtshipDanceCommand,
		LP_FieldRandomStigmaIncinerate,
		LP_FieldStigmaObjectDec,
		LP_DemianFlyingSwordCreate,
		LP_DemianFlyingSwordMakeEnterRequest,
		LP_DemianFlyingSwordMakeEnterInfo,
		LP_DemianFlyingSwordNode,
		LP_DemianFlyingSwordTarget,
		LP_DemianCorruption,

		#pragma region FIELD_HUNDREDBINGO
		LP_BEGIN_FIELD_HUNDREDBINGO,
		LP_HBingoBingoGame = LP_BEGIN_FIELD_HUNDREDBINGO,
		LP_HBingoHostNumber,
		LP_HBingoHostNumberReady,
		LP_HBingoAddRank,
		LP_HBingoRemoveRank,
		LP_HBingoFinishRank,
		LP_HBingoCheckNumberAck,
		LP_HBingoGameState,
		LP_END_FIELD_HUNDREDBINGO = LP_HBingoGameState,
		#pragma endregion

		#pragma region FIELD_TYPINGGAME
		LP_BEGIN_FIELD_TYPINGGAME,
		LP_TypingGameWaveInfo = LP_BEGIN_FIELD_TYPINGGAME,
		LP_TypingGameEnter,
		LP_TypingGameMoveToPortal,
		LP_TypingGameStart,
		LP_TypingGameResetWord,
		LP_TypingGameScore,
		LP_TypingGameResult,
		LP_TypingGameEffect,
		LP_TypingGameState,
		LP_TypingGamePointEffect,
		LP_TypingGameUserSkillAttack,
		LP_TypingGameSummon,
		LP_END_FIELD_TYPINGGAME = LP_TypingGameSummon,
		#pragma endregion

		#pragma region FIELD_HUNDREDOXQUIZ
		LP_BEGIN_FIELD_HUNDREDOXQUIZ,
		LP_HOxQuizState = LP_BEGIN_FIELD_HUNDREDOXQUIZ,
		LP_HOxQuizEnter,
		LP_HOxQuizQuestions,
		LP_HOxQuizExplan,
		LP_HOxQuizCountEffect,
		LP_HOxQuizMoveToPortal,
		LP_HOxQuizResult,
		LP_END_FIELD_HUNDREDOXQUIZ = LP_HOxQuizResult,
		#pragma endregion

		#pragma region FIELD_STARPLANETRPS
		LP_BEGIN_FIELD_STARPLANETRPS,
		LP_SPRpsGameInit = LP_BEGIN_FIELD_STARPLANETRPS,
		LP_SPRpsGameState,
		LP_SPRpsGameReady,
		LP_SPRpsGameStart,
		LP_SPRpsGameScore,
		LP_SPRpsGameLeaveAck,
		LP_SPRpsGameResult,
		LP_END_FIELD_STARPLANETRPS = LP_SPRpsGameResult,
		#pragma endregion

		#pragma region FIELD_SIDESCROLLFLYSHOOTING
		LP_BEGIN_FIELD_SIDESCROLLFLYSHOOTING,
		LP_SSFSGameInit = LP_BEGIN_FIELD_SIDESCROLLFLYSHOOTING,
		LP_SSFSReady,
		LP_SSFSStart,
		LP_SSFSClear,
		LP_SSFSFail,
		LP_SSFSUserInfo,
		LP_SSFSLethalAttack,
		LP_SSFSGameResult,
		LP_END_FIELD_SIDESCROLLFLYSHOOTING = LP_SSFSGameResult,
		#pragma endregion

		#pragma region FIELDSTATE
		LP_BEGIN_FIELDSTATE,
		LP_FieldState_s = LP_BEGIN_FIELDSTATE,
		LP_StarPlanet_HBingoHostNumber,
		LP_StarPlanet_HBingoAddRank,
		LP_StarPlanet_HBingoRemoveRank,
		LP_StarPlanet_HBingoCheckNumberAck,
		LP_StarPlanet_HBingoGameState,
		LP_StarPlanet_HBingoBingoGame,
		LP_StarPlanet_HRpsGame,
		LP_StarPlanet_HRpsGameState,
		LP_StarPlanet_HRpsResult,
		LP_StarPlanet_HRpsRoundResult,
		LP_StarPlanet_HRpsSelectEffect,
		LP_StarPlanet_HRpsEnterIntrusionUser,
		LP_StarPlanet_PhotoGameNpcAction,
		LP_StarPlanet_PhotoGameState,
		LP_StarPlanet_GroupDance,
		LP_StarPlanet_GroupDanceState,
		LP_StarPlanet_GroupDanceResult,
		LP_StarPlanet_GroupDanceRoundResult,
		LP_StarPlanet_GroupDanceNpcAction,
		LP_StarPlanet_GroupDanceSelectEffect,
		LP_FieldState_e,
		LP_END_FIELDSTATE = LP_FieldState_e,
		#pragma endregion

		#pragma region BATTLEUSERPOOL
		LP_BEGIN_BATTLEUSERPOOL = 1365,
		LP_BattleUserPool_s = LP_BEGIN_BATTLEUSERPOOL,
		LP_RegisterBattleUser,
		LP_UnRegisterBattleUser,
		LP_BattleUserInfo,
		LP_ValidBattleUser,
		LP_JobSelectResult,
		LP_ChampSelectTimer,
		LP_BattleUserRespawnUI,
		LP_BattlePvPPointEffect,
		LP_BattleUserPool_e,
		LP_END_BATTLEUSERPOOL = LP_BattleUserPool_e,
		#pragma endregion

		#pragma region BATTLEATTACKMAN
		LP_BEGIN_BATTLEATTACKMAN,
		LP_BattleAttackMan_s = LP_BEGIN_BATTLEATTACKMAN,
		LP_SetBattleAttack,
		LP_SetBattleAttackExpire,
		LP_SetBattleAttackPosition,
		LP_NextBattleAttack,
		LP_RepeatBattleAttack,
		LP_BattleAttackMan_e,
		LP_END_BATTLEATTACKMAN = LP_BattleAttackMan_e,
		#pragma endregion

		#pragma region TEMPORARY_SKILL
		LP_BEGIN_TEMPORARY_SKILL,
		LP_TemporarySkillMan_s = LP_BEGIN_TEMPORARY_SKILL,
		LP_SetTemporarySkillSet,
		LP_UsedTemporarySkill,
		LP_ValidateTemporarySkill,
		LP_ValidateTemporarySkillSet,
		LP_ResetCoolTimeSkillSet,
		LP_TemporarySkillMan_e,
		LP_END_TEMPORARY_SKILL = LP_TemporarySkillMan_e,
		#pragma endregion

		LP_ZakumTimer,
		LP_END_ETCFIELDOBJ = LP_ZakumTimer,
		#pragma endregion

		#pragma region SCRIPT
		LP_BEGIN_SCRIPT,
		LP_ScriptMessage = LP_BEGIN_SCRIPT,
		LP_END_SCRIPT = LP_ScriptMessage,
		#pragma endregion

		#pragma region SHOP
		LP_BEGIN_SHOP,
		LP_OpenShopDlg = LP_BEGIN_SHOP,
		LP_ShopResult,
		LP_END_SHOP = LP_ShopResult,
		#pragma endregion

		#pragma region ADMINSHOP
		LP_BEGIN_ADMINSHOP,
		LP_AdminShopResult = LP_BEGIN_ADMINSHOP,
		LP_AdminShopCommodity,
		LP_END_ADMINSHOP = LP_AdminShopCommodity,
		#pragma endregion

		LP_BEGIN_UNK2,
			LP_UNK2_Unk1 = LP_BEGIN_UNK2,
			LP_UNK2_Unk2,
			LP_UNK2_Unk3,
			LP_UNK2_Unk4,
			LP_UNK2_Unk5,
			LP_UNK2_Unk6,
		LP_END_UNK2 = LP_UNK2_Unk6,

		#pragma region SOULDUNGEON
		LP_BEGIN_SOULDUNGEON,
		LP_SoulDungeonStart = LP_BEGIN_SOULDUNGEON,
		LP_SoulDungeon_SoulPiece_Change,
		LP_SoulDungeon_SoulItem_UseVoteRequest,
		LP_SoulDungeon_SoulItem_UseResult,
		LP_SoulDungeon_SoulItem_MapInfo,
		LP_SoulDungeon_SoulItem_MapInfo_Close,
		LP_SoulDungeon_SoulItem_DataChange,
		LP_SoulDungeon_SoulItem_VoteResult,
		LP_SoulDungeon_Effect,
		LP_SoulDungeon_MiniMapInfo,
		LP_SoulDungeonEnd,
		LP_END_SOULDUNGEON = LP_SoulDungeonEnd,
		#pragma endregion

		#pragma region COORDINAITON
		LP_BEGIN_COORDINAITON,
		LP_CoordinationStart = LP_BEGIN_COORDINAITON,
		LP_Coordination_RunWay_Avata,
		LP_CoordinationEnd,
		LP_END_COORDINAITON = LP_CoordinationEnd,
		#pragma endregion

		LP_TrunkResult,

		#pragma region STOREBANK
		LP_BEGIN_STOREBANK,
		LP_StoreBankGetAllResult = LP_BEGIN_STOREBANK,
		LP_StoreBankResult,
		LP_END_STOREBANK = LP_StoreBankResult,
		#pragma endregion

		LP_RPSGame,
		LP_GSRPSGame,
		LP_StarPlanet_GSRPSGame,
		LP_Messenger,
		LP_MiniRoom,
		LP_SetCashShopInitialItem,
		LP_TryMigrateCashShop,

		#pragma region TOURNAMENT
		LP_BEGIN_TOURNAMENT,
		LP_Tournament = LP_BEGIN_TOURNAMENT,
		LP_TournamentMatchTable,
		LP_TournamentSetPrize,
		LP_TournamentNoticeUEW,
		LP_TournamentAvatarInfo,
		LP_END_TOURNAMENT = LP_TournamentAvatarInfo,
		#pragma endregion

		#pragma region WEDDING
		LP_BEGIN_WEDDING,
		LP_WeddingProgress = LP_BEGIN_WEDDING,
		LP_WeddingCremonyEnd,
		LP_END_WEDDING = LP_WeddingCremonyEnd,
		#pragma endregion

		#pragma region GHOSTPARK
		LP_BEGIN_GHOSTPARK = 1449,
		LP_GhostParkFieldStart = LP_BEGIN_GHOSTPARK,
		LP_GhostParkRuneUseAck,
		LP_GhostParkRuneAppear,
		LP_GhostParkRuneDisappear,
		LP_GhostParkSetKilledMobExpRate,
		LP_GhostParkSetCurseLevelExpRate,
		LP_GhostParkHomingBulletCreate,
		LP_GhostParkFieldEnd,
		LP_END_GHOSTPARK = LP_GhostParkFieldEnd,
		#pragma endregion

		LP_BEGIN_UNK3,
			LP_UNK3_Unk1 = LP_BEGIN_UNK3,
			LP_UNK3_Unk2,
			LP_UNK3_Unk3,
		LP_END_UNK3 = LP_UNK3_Unk3,

		LP_Parcel,
		LP_END_FIELD = LP_Parcel,
		#pragma endregion

		#pragma region CASHSHOP
		LP_BEGIN_CASHSHOP,
			LP_CashShopChargeParamResult = LP_BEGIN_CASHSHOP,
			LP_CashShopQueryCashResult,
			LP_CashShopCashItemResult,
			LP_CashShopPurchaseExpChanged,
			LP_CashShopGiftMateInfoResult,
			LP_CashShopCharStatChanged,
			LP_CashShopTerminated,
			LP_CashShopRedrawList,
			LP_CashCoodinaionResult,
			LP_CashShopScreenMsg,
			LP_CashShop_MVP_ItemGive_Result,
			LP_CashShopCheckMileageResult,
			LP_CashShopChargeMileageNotice,
			LP_CashShopNaverUsageInfoResult,
			LP_CashShopUnk1,
			LP_CashShopUnk2,
			LP_CashShopUnk3,
			LP_CashShopUnk4,
			LP_CashShopUnk5,
			LP_CashShopUnk6,
			LP_CashShopUnk7,
			LP_CashShopUnk8,
			LP_CashShopUnk9,
			LP_CashShopUnkA,
			LP_CashShopUnkB,
			LP_CashShopUnkC,
			LP_CashShopUnkD,
			LP_CashShopUnkE,
			LP_CashShopMemberShopResult,
		LP_END_CASHSHOP = LP_CashShopMemberShopResult,
		#pragma endregion

		LP_BEGIN_UICONTEXT,
		LP_UIContext_s = LP_BEGIN_UICONTEXT,
		LP_AttendanceEventData,
		LP_AttendanceEventUIData,
		LP_EventUIData,
		LP_EventUIAck,
		LP_GhostPaintsPointUpdate,
		LP_UserTimerInfo,
		LP_EventRanking_Open,
		LP_SADResultUI_Open,
		LP_SADLevelUpEquipDiff,
		LP_GrowthHelper,
		LP_ContentsMap,
		LP_UrusShop,
		LP_DailyGift,
		LP_SlidePuzzle,
		LP_Disguise,
		LP_UIContext_e,
		LP_END_UICONTEXT = LP_UIContext_e,

		LP_BEGIN_DEBUGONLY,
		LP_DEBUG_s = LP_BEGIN_DEBUGONLY,
		LP_DEBUG_RECT_MOBSKILL,
		LP_DEBUG_RECT_HIDDENCHECKPOINT,
		LP_DEBUG_e,
		LP_END_DEBUGONLY = LP_DEBUG_e,

		#pragma region EVENTGROUP
		LP_BEGIN_EVENTGROUP = 1533,
			LP_EventGroup_s = LP_BEGIN_EVENTGROUP,
			LP_EventGroupInvitationInfo,
			LP_EventGroupInvitation,
			LP_EventGroupInvitationFail,
			LP_EventGroupInvitationAccept,
			LP_EventGroupInfo,
			LP_EventGroupFail,

			#pragma region EVENTGROUPPACKET
			LP_BEGIN_EVENTGROUPPACKET,
				LP_EventGroupState = LP_BEGIN_EVENTGROUPPACKET,
				LP_EventGroupLeave,
			LP_END_EVENTGROUPPACKET = LP_EventGroupLeave,
			#pragma endregion
			LP_EventGroup_e,
		LP_END_EVENTGROUP = LP_EventGroup_e,
		#pragma endregion

		#pragma region STARPLANET_MATCHING
		LP_BEGIN_STARPLANET_MATCHING,
			LP_StarPlanetMatching_s = LP_BEGIN_STARPLANET_MATCHING,
			LP_StarPlanetMatching_OpenUI,
			LP_StarPlanetMatching_RegisterAck,
			LP_StarPlanetMatching_UnRegisterAck,
			LP_StarPlanetMatching_WaitAssent,
			LP_StarPlanetMatching_Transfer,
			LP_StarPlanetMatching_Error,
			LP_StarPlanetMatching_e,
		LP_END_STARPLANET_MATCHING = LP_StarPlanetMatching_e,
		#pragma endregion

		#pragma region STARPLANET_INVITATION
		LP_BEGIN_STARPLANET_INVITATION,
			LP_StarPlanetInvitation_s = LP_BEGIN_STARPLANET_INVITATION,
			LP_StarPlanetInvitation_RunMatching,
			LP_StarPlanetInvitation_RegisterAck,
			LP_StarPlanetInvitation_End,
			LP_StarPlanetInvitation_e,
		LP_END_STARPLANET_INVITATION = LP_StarPlanetInvitation_e,
		#pragma endregion

		#pragma region FUNCKEYMAPPED
		LP_BEGIN_FUNCKEYMAPPED,
			LP_FuncKeyMappedInit = LP_BEGIN_FUNCKEYMAPPED,
			LP_PetConsumeItemInit,
			LP_PetAutoBuff,
			LP_PetConsumeMPItemInit,
		LP_END_FUNCKEYMAPPED = LP_PetConsumeMPItemInit,
		#pragma endregion

		LP_CheckSPWOnCreateNewCharacterResult,
		LP_SetSPWResult,

		#pragma region CHARACTERSALE
		LP_BEGIN_CHARACTERSALE,
			LP_CheckDuplicatedIDResultInCS = LP_BEGIN_CHARACTERSALE,
			LP_CreateNewCharacterResultInCS,
			LP_CreateNewCharacterFailInCS,
			LP_CharacterSale,
		LP_END_CHARACTERSALE = LP_CharacterSale,
		#pragma endregion

		#pragma region GOLDHAMMER
		LP_BEGIN_GOLDHAMMER,
			LP_GoldHammere_s = LP_BEGIN_GOLDHAMMER,
			LP_GoldHammerResult,
			LP_GoldHammere_e,
		LP_END_GOLDHAMMER = LP_GoldHammere_e,
		#pragma endregion

		#pragma region PLATINUMHAMMER
		LP_BEGIN_PLATINUMHAMMER,
			LP_PlatinumHammere_s = LP_BEGIN_PLATINUMHAMMER,
			LP_PlatinumHammerResult,
			LP_PlatinumHammere_e,
		LP_END_PLATINUMHAMMER = LP_PlatinumHammere_e,
		#pragma endregion

		#pragma region EGOEQUIP
		LP_BEGIN_EGOEQUIP,
			LP_EgoEquip_s = LP_BEGIN_EGOEQUIP,
			LP_EgoEquipGaugeCompleteReturn,
			LP_EgoEquipCreateUpgradeItemCostInfo,
			LP_EgoEquipCheckUpgradeItemResult,
			LP_EgoEquipItemUpgradeEffect,
			LP_EgoEquip_e,
		LP_END_EGOEQUIP = LP_EgoEquip_e,
		#pragma endregion

		#pragma region INHERITANCE
		LP_BEGIN_INHERITANCE,
			LP_Inheritance_s = LP_BEGIN_INHERITANCE,
			LP_InheritanceInfo,
			LP_InheritanceComplete,
			LP_Inheritance_e,
		LP_END_INHERITANCE = LP_Inheritance_e,
		#pragma endregion

		#pragma region MIRROR_READING
		LP_BEGIN_MIRROR_READING,
			LP_MirrorReading_s = LP_BEGIN_MIRROR_READING,
			LP_MirrorReadingSelectBookResult,
			LP_MirrorReading_e,
		LP_END_MIRROR_READING = LP_MirrorReading_e,
		#pragma endregion

		#pragma region FIELDATTACKOBJPOOL
		LP_BEGIN_FIELDATTACKOBJPOOL,
			LP_FIELDATTACKOBJ_CREATE = LP_BEGIN_FIELDATTACKOBJPOOL,
			LP_FIELDATTACKOBJ_REMOVE_BYSINGLEKEY,
			LP_FIELDATTACKOBJ_REMOVE_BYLIST,
			LP_FIELDATTACKOBJ_REMOVE_ALL,

			#pragma region FIELDATTACKOBJ
			LP_BEGIN_FIELDATTACKOBJ,
				LP_FIELDATTACKOBJ_S = LP_BEGIN_FIELDATTACKOBJ,
				LP_FIELDATTACKOBJ_SETATTACK,
				LP_FIELDATTACKOBJ_SETOWNER,
				LP_FIELDATTACKOBJ_RESETOWNER,
				LP_FIELDATTACKOBJ_PUSHACT,
				LP_FIELDATTACKOBJ_E,
			LP_END_FIELDATTACKOBJ = LP_FIELDATTACKOBJ_E,
			#pragma endregion
			LP_FIELDATTACKOBJ_SENDALL,
		LP_END_FIELDATTACKOBJPOOL = LP_FIELDATTACKOBJ_SENDALL,
		#pragma endregion

		#pragma region UNK1
		LP_BEGIN_UNK1,
			LP_UNK1_UNK1 = LP_BEGIN_UNK1,
			LP_UNK1_UNK2,
			LP_UNK1_UNK3,
			LP_UNK1_UNK4,
		LP_END_UNK1 = LP_UNK1_UNK4,
		#pragma endregion

		#pragma region BATTLERECORD
		LP_BEGIN_BATTLERECORD,
			LP_BattleRecord_s = LP_BEGIN_BATTLERECORD,
			LP_BattleRecordDotDamageInfo,
			LP_BattleRecordKillDamageInfo,
			LP_BattleRecordBattleDamageInfo,
			LP_BattleRecordRequestResult,
			LP_BattleRecordAggroInfo,
			LP_BattleRecordSkillDamageLog,
			LP_BattleRecord_e,
		LP_END_BATTLERECORD = LP_BattleRecord_e,
		#pragma endregion

		LP_BEGIN_FARM = 0x4EF,
		LP_FARM_S = 0x4EF,

		LP_BEGIN_FARMFIELD = 0x4F0,
		LP_FARMFIELD_S = 0x4F0,
		LP_UpdateFarmInventory = 0x4F1,
		LP_ConsoleMessage = 0x4F2,
		LP_ResultObjectInteract = 0x4F3,
		LP_ResultConsumeObject = 0x4F4,
		LP_ResultDictionary = 0x4F5,
		LP_ResultBuyObject = 0x4F6,
		LP_ResultSelObject = 0x4F7,
		LP_FarmMonsterCombineResult = 0x4F8,
		LP_FarmMonsterSearchResult = 0x4F9,
		LP_RequestFarmVisitResult = 0x4FA,
		LP_UpdateNewsfeed = 0x4FB,
		LP_UpdateDictionary = 0x4FC,
		LP_RequestAutoHarvestResult = 0x4FD,
		LP_RequestSoulRechargeResult = 0x4FE,
		LP_FARMFIELD_E = 0x4FF,
		LP_END_FARMFIELD = 0x4FF,

		LP_BEGIN_FARMUSER = 0x500,
		LP_FARMUSER_S = 0x500,
		LP_SetFarmUser = 0x501,
		LP_SetFarmInventory = 0x502,
		LP_SetFarmQuestAll = 0x503,
		LP_SendQuestMessage = 0x504,
		LP_NoticeMessage = 0x505,
		LP_UpdateMonsterList = 0x506,
		LP_UpdateFarmDeco = 0x507,
		LP_UpdateFarmPoint = 0x508,
		LP_UpdateFarmCash = 0x509,
		LP_UpdateFarmTheme = 0x50A,
		LP_UpdateFarmMonsterSlot = 0x50B,
		LP_UpdateFarmMonsterLockerSlot = 0x50C,
		LP_UpdateFarmExp = 0x50D,
		LP_ResultCheckFarmName = 0x50E,
		LP_ResultCheckFarmNameByConsume = 0x50F,
		LP_ResultCompleteQuest = 0x510,
		LP_ResultGetPhoto = 0x511,
		LP_ResultUpdatePhoto = 0x512,
		LP_ResultRefillDailyQuest = 0x513,
		LP_SendFarmGift = 0x514,
		LP_SendFriendList = 0x515,
		LP_SendFriendOnline = 0x516,
		LP_ResultAddFriend = 0x517,
		LP_ResultSendNotice = 0x518,
		LP_ResultLoadMainLog = 0x519,
		LP_ResultAddBlackList = 0x51A,
		LP_ResultFarmUserInfoUI = 0x51B,
		LP_SetGuestOwnerInfo = 0x51C,
		LP_FarmWhisper = 0x51D,
		LP_FarmGroupMessage = 0x51E,
		LP_FarmBroadcastMsg = 0x51F,
		LP_ResultFarmFriendRecommend = 0x520,
		LP_FarmRequestSetInGameInfo = 0x521,
		LP_FarmRequestForcedShopOpen = 0x522,
		LP_FarmRequestAskSetInGameInfo = 0x523,
		LP_FarmResultSetInGameInfo = 0x524,
		LP_InGameFriendRequestResult = 0x525,
		LP_InGameFriendEventNotice = 0x526,
		LP_FarmWorldWhisperResult = 0x527,
		LP_ResultFarmStaticInfo = 0x528,
		LP_FARMUSER_E = 0x529,
		LP_END_FARMUSER = 0x529,

		LP_BEGIN_FARMMONSTER = 0x52A,
		LP_FARMMONSTER_S = 0x52A,
		LP_FarmMonsterInsert = 0x52B,
		LP_FarmMonsterUpdate = 0x52C,
		LP_FarmMonsterUpdateMy = 0x52D,
		LP_FarmMonsterSetNameResult = 0x52E,
		LP_FarmMonsterCareResult = 0x52F,
		LP_FarmMonsterPlayResult = 0x530,
		LP_FarmMonsterReleaseResult = 0x531,
		LP_FarmMonsterLockerResult = 0x532,
		LP_FarmMonsterExtendLifeResult = 0x533,
		LP_FARMMONSTER_E = 0x534,
		LP_END_FARMMONSTER = 0x534,

		LP_FARM_E = 0x535,
		LP_END_FARM = 0x535,

		LP_NO = 0x536,
	};
};